version: 2  # Required

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

python:
   install:
   - requirements: docs/requirements-rtd.txt

formats: all
