# This file was generated by stubgen-pyx v0.2.12 from h5py\_conv.pyx

from logging import Logger, getLogger

from .defs import *
from .h5 import H5PYConfig, get_config

cfg: H5PYConfig = get_config()
logger: Logger = getLogger(__name__)

def register_converters() -> int:
    ...

def unregister_converters() -> int:
    ...
