# This file was generated by stubgen-pyx v0.2.10 from h5py\_conv.pyx

"""
Low-level type-conversion routines.
"""
from logging import getLogger

from .defs import *
from .h5 import get_config

cfg = get_config()
logger = getLogger(__name__)

def register_converters() -> int:
    ...

def unregister_converters() -> int:
    ...