# This file was generated by stubgen-pyx v0.2.11 from h5py\_conv.pyx

from logging import getLogger

from .defs import *
from .h5 import get_config

cfg = get_config()
logger = getLogger(__name__)

def register_converters() -> int:
    ...

def unregister_converters() -> int:
    ...