# This file was generated by stubgen-pyx v0.2.12 from h5py\_errors.pyx

from typing import Type
from typing import TypeAlias as _TypeAlias

from .api_types_hdf5 import *

H5E_major_t: _TypeAlias = int
H5E_minor_t: _TypeAlias = int
H5E_direction_t: _TypeAlias = int
_minor_table: dict[int, Type[Exception]] = ...
_exact_table: dict[tuple[int, int], Type[Exception]] = ...

def silence_errors() -> None:
    ...

def unsilence_errors() -> None:
    ...
