# This file was generated by stubgen-pyx v0.2.11 from h5py\_errors.pyx

from typing import TypeAlias as _TypeAlias

from .api_types_hdf5 import *

H5E_major_t: _TypeAlias = int
H5E_minor_t: _TypeAlias = int
H5E_direction_t: _TypeAlias = int
_minor_table = ...
_exact_table = ...

def silence_errors():
    ...

def unsilence_errors():
    ...