class FastRLock:
    def __cinit__(self) -> None: ...
    def __dealloc__(self) -> None: ...
    def acquire(self, blocking: bool = True) -> bool: ...
    def release(self) -> None: ...
    def __enter__(self) -> bool: ...
    def __exit__(self, t, v, tb) -> None: ...
    def _is_owned(self) -> bool: ...
