# This file was generated by stubgen-pyx v0.2.12 from h5py\_npystrings.pyx

from .defs import *


def npystrings_pack(space: hid_t, contig: int, noncontig: int, descr: int) -> None:
    ...

def npystrings_unpack(space: hid_t, contig: int, noncontig: int, descr: int, npoints: int):
    ...
