# This file was generated by stubgen-pyx v0.2.10 from h5py\_npystrings.pyx

"""Support for NpyStrings - NumPy's native variable-width strings.

This module requires NumPy >=2.0 to be imported. To allow the rest of h5py
to work with NumPy 1.x installed, this module must be imported conditionally
and can't be cimport'ed.
"""
from .defs import *


def npystrings_pack(space: hid_t, contig: int, noncontig: int, descr: int):
    """Convert a zero-terminated char**, which is the in-memory representation
    for a HDF5 variable-width string dataset, into a NpyString array
    (NumPy's native variable-width strings dtype).

    Parameters
    ----------
    space : hid_t
        HDF5 dataspace ID for the output non-contiguous buffer
        containing packed NpyStrings
    contig : void * (actually a char **)
        Input buffer for the contiguous zero-terminated char **
    noncontig : void *
        Output buffer for the non-contiguous packed NpyStrings
    descr : PyArray_Descr * (actually a PyArray_StringDTypeObject *)
        NumPy dtype descriptor for the NpyStrings
    npoints : size_t
        Number of points to copy

    Notes
    -----
    This function deep-copies the input zero-terminated strings.
    Memory management for the outputs is handled by NumPy.

    This function defines a pure-python API interface to _proxy.pyx.
    This is necessary to allow this module to be conditionally imported,
    allowing NumPy 1.x to continue working everywhere else.
    """

def npystrings_unpack(space: hid_t, contig: int, noncontig: int, descr: int, npoints: int):
    """Convert a NpyString array (NumPy's native variable-width strings dtype)
    to a zero-terminated char**, which is the in-memory representation for a
    HDF5 variable-width string dataset.

    Parameters
    ----------
    space : hid_t
        HDF5 dataspace ID for the input non-contiguous buffer
        containing packed NpyStrings
    contig : void * (actually a char **)
        Output buffer for the contiguous zero-terminated char **
    noncontig : void *
        Input buffer for the non-contiguous packed NpyStrings
    descr : PyArray_Descr * (actually a PyArray_StringDTypeObject *)
        NumPy dtype descriptor for the NpyStrings
    npoints : size_t
        Number of points to copy

    Returns
    -------
    char *
        A temporary buffer containing the zero-terminated strings.
        This buffer must be freed after writing to disk.

        Note that this always the same as contig[0] when this
        function returns, but H5Tconvert may change the contents
        of contig[0] in place later on.

    Notes
    -----
    This function defines a pure-python API interface to _proxy.pyx.
    This is necessary to allow this module to be conditionally imported,
    allowing NumPy 1.x to continue working everywhere else.
    """