# This file was generated by stubgen-pyx v0.2.11 from h5py\_objects.pyx

from .defs import *


class BogoLock:

    def __enter__(self):
        ...

    def __exit__(self, *args):
        ...

class FastRLock:

    def __cinit__(self):
        ...

    def __dealloc__(self):
        ...

    def acquire(self, blocking: bool=True):
        ...

    def release(self):
        ...

    def __enter__(self):
        ...

    def __exit__(self, t, v, tb):
        ...

    def _is_owned(self):
        ...

class ObjectID:
    locked: int

    @property
    def fileno(self):
        ...

    @property
    def valid(self):
        ...

    def __cinit__(self, id_):
        ...

    def __dealloc__(self):
        ...

    def _close(self, _phil=..., warn=..., debug_message='CLOSE -'):
        ...

    def close(self):
        ...

    def __bool__(self):
        ...

    def __copy__(self):
        ...

    def __richcmp__(self, other: object, how: int):
        ...

    def __hash__(self):
        ...
phil = ...

def with_phil(func):
    ...

def _phil_before_fork():
    ...

def _phil_after_fork():
    ...

def wvd_values(self):
    ...

def wvd_items(self):
    ...

@with_phil
def print_reg():
    ...

@with_phil
def nonlocal_close():
    ...