# This file was generated by stubgen-pyx v0.2.12 from h5py\_objects.pyx

from threading import RLock
from typing import Callable, Iterable, ParamSpec, TypeVar

from .defs import *


class BogoLock:

    def __enter__(self) -> None:
        ...

    def __exit__(self, *args) -> None:
        ...

class FastRLock:

    def __cinit__(self) -> None:
        ...

    def __dealloc__(self) -> None:
        ...

    def acquire(self, blocking: bool=True) -> bool:
        ...

    def release(self) -> None:
        ...

    def __enter__(self) -> bool:
        ...

    def __exit__(self, t, v, tb) -> None:
        ...

    def _is_owned(self) -> bool:
        ...

class ObjectID:
    locked: int

    @property
    def fileno(self) -> tuple[int, int]:
        ...

    @property
    def valid(self) -> int:
        ...

    def __cinit__(self, id_) -> None:
        ...

    def __dealloc__(self) -> None:
        ...

    def _close(self, _phil=..., warn=..., debug_message='CLOSE -') -> None:
        ...

    def close(self) -> None:
        ...

    def __bool__(self) -> int:
        ...

    def __copy__(self) -> ObjectID:
        ...

    def __richcmp__(self, other: object, how: int) -> bool:
        ...

    def __hash__(self) -> int:
        ...
phil: RLock | BogoLock | FastRLock = ...
P = ParamSpec('P')
T = TypeVar('T')

def with_phil(func: Callable[P, T]) -> Callable[P, T]:
    ...

def _phil_before_fork() -> None:
    ...

def _phil_after_fork() -> None:
    ...

def wvd_values(self) -> Iterable[object]:
    ...

def wvd_items(self) -> Iterable[tuple[int, ObjectID]]:
    ...

@with_phil
def print_reg() -> None:
    ...

@with_phil
def nonlocal_close() -> None:
    ...
