# This file was generated by stubgen-pyx v0.2.10 from h5py\_objects.pyx

"""
Implements ObjectID base class.
"""
from .defs import *


class BogoLock:

    def __enter__(self):
        ...

    def __exit__(self, *args):
        ...

class FastRLock:
    """Fast, re-entrant locking.

    Under uncongested conditions, the lock is never acquired but only
    counted.  Only when a second thread comes in and notices that the
    lock is needed, it acquires the lock and notifies the first thread
    to release it when it's done.  This is all made possible by the
    wonderful GIL.
    """

    def __cinit__(self):
        ...

    def __dealloc__(self):
        ...

    def acquire(self, blocking: bool=True):
        ...

    def release(self):
        ...

    def __enter__(self):
        ...

    def __exit__(self, t, v, tb):
        ...

    def _is_owned(self):
        ...

class ObjectID:
    """
        Represents an HDF5 identifier.

    attributes:
    cdef object __weakref__
    cdef readonly hid_t id
    cdef public int locked              # Cannot be closed, explicitly or auto
    cdef object _hash
    cdef size_t _pyid
    """
    locked: int

    @property
    def fileno(self):
        ...

    @property
    def valid(self):
        ...

    def __cinit__(self, id_):
        ...

    def __dealloc__(self):
        ...

    def _close(self, _phil=..., warn=..., debug_message='CLOSE -'):
        """ Manually close this object. """

    def close(self):
        """ Close this identifier. """

    def __bool__(self):
        ...

    def __copy__(self):
        ...

    def __richcmp__(self, other: object, how: int):
        """ Default comparison mechanism for HDF5 objects (equal/not-equal)

        Default equality testing:
        1. Objects which are not both ObjectIDs are unequal
        2. Objects with the same HDF5 ID number are always equal
        3. Objects which hash the same are equal
        """

    def __hash__(self):
        """ Default hashing mechanism for HDF5 objects

        Default hashing strategy:
        1. Try to hash based on the object's fileno and objno records
        2. If (1) succeeds, cache the resulting value
        3. If (1) fails, raise TypeError
        """
phil = ...

def with_phil(func):
    """ Locking decorator """

def _phil_before_fork():
    """
    Acquire the `phil` lock before forking so no thread other
    than the current (forking) thread is holding the lock.
    """

def _phil_after_fork():
    """
    Release the lock after forking in both the parent and the child.
    """

def wvd_values(self):
    ...

def wvd_items(self):
    ...

@with_phil
def print_reg():
    ...

@with_phil
def nonlocal_close():
    """ Find dead ObjectIDs and set their integer identifiers to 0.
    """