# This file was generated by stubgen-pyx v0.2.10 from h5py\_proxy.pyx

"""
Proxy functions for read/write, to work around the HDF5 bogus type issue.
"""
from typing import TypeAlias as _TypeAlias

from .defs import *

copy_dir: _TypeAlias = int