# This file was generated by stubgen-pyx v0.2.12 from h5py\_selector.pyx

import numpy as np

from ._hl.selections import FancySelection, SimpleSelection
from ._objects import with_phil
from .defs import *
from .h5d import DatasetID
from .h5s import SpaceID


class Selector:

    def __cinit__(self, space: SpaceID) -> None:
        ...

    def __dealloc__(self) -> None:
        ...

    @with_phil
    def make_selection(self, args: tuple) -> SimpleSelection | FancySelection:
        ...

class Reader:

    def __cinit__(self, dsid: DatasetID) -> None:
        ...

    @with_phil
    def read(self, args: tuple) -> np.ndarray:
        ...

class MultiBlockSlice:

    def __init__(self, start=0, stride=1, count=None, block=1) -> None:
        ...

    def indices(self, length) -> tuple[int, int, int, int]:
        ...

    def _repr(self, count=None) -> str:
        ...

    def __repr__(self) -> str:
        ...
