# This file was generated by stubgen-pyx v0.2.10 from h5py\_selector.pyx

"""Class to efficiently select and read data from an HDF5 dataset

This is written in Cython to reduce overhead when reading small amounts of
data. The core of it is translating between numpy-style slicing & indexing and
HDF5's H5Sselect_hyperslab calls.

Python & numpy distinguish indexing a[3] from slicing a single element a[3:4],
but there is no equivalent to this when selecting data in HDF5. So we store a
separate boolean ('scalar') for each dimension to distinguish these cases.
"""
from ._objects import with_phil
from .defs import *
from .h5d import DatasetID
from .h5s import SpaceID


class Selector:

    def __cinit__(self, space: SpaceID):
        ...

    def __dealloc__(self):
        ...

    @with_phil
    def make_selection(self, args: tuple):
        """Apply indexing/slicing args and create a high-level selection object

        Returns an instance of SimpleSelection or FancySelection, with a copy
        of the selector's dataspace.
        """

class Reader:

    def __cinit__(self, dsid: DatasetID):
        ...

    @with_phil
    def read(self, args: tuple):
        """Index the dataset using args and read into a new numpy array

        Only works for simple numeric dtypes.
        """

class MultiBlockSlice:
    """
    A conceptual extension of the built-in slice object to allow selections
    using start, stride, count and block.

    If given, these parameters will be passed directly to
    H5Sselect_hyperslab. The defaults are start=0, stride=1, block=1,
    count=length, which will select the full extent.

    __init__(start, stride, count, block) => Create a new MultiBlockSlice, storing
        any given selection parameters and using defaults for the others
    start => The offset of the starting element of the specified hyperslab
    stride => The number of elements between the start of one block and the next
    count => The number of blocks to select
    block => The number of elements in each block

    """

    def __init__(self, start=0, stride=1, count=None, block=1):
        ...

    def indices(self, length):
        """Calculate and validate start, stride, count and block for the given length"""

    def _repr(self, count=None):
        ...

    def __repr__(self):
        ...