# This file was generated by stubgen-pyx v0.2.11 from h5py\_selector.pyx

from ._objects import with_phil
from .defs import *
from .h5d import DatasetID
from .h5s import SpaceID


class Selector:

    def __cinit__(self, space: SpaceID):
        ...

    def __dealloc__(self):
        ...

    @with_phil
    def make_selection(self, args: tuple):
        ...

class Reader:

    def __cinit__(self, dsid: DatasetID):
        ...

    @with_phil
    def read(self, args: tuple):
        ...

class MultiBlockSlice:

    def __init__(self, start=0, stride=1, count=None, block=1):
        ...

    def indices(self, length):
        ...

    def _repr(self, count=None):
        ...

    def __repr__(self):
        ...