# This file was generated by stubgen-pyx v0.2.10 from h5py\api_types_ext.pxd

from typing import TypeAlias as _TypeAlias

int: _TypeAlias = int
int: _TypeAlias = int
PyObject: _TypeAlias = None
int: _TypeAlias = int
Py_uintptr_t: _TypeAlias = int