# This file was generated by stubgen-pyx v0.2.11 from h5py\api_types_hdf5.pxd

from typing import TypeAlias as _TypeAlias

from .api_types_ext import *

H5_iter_order_t: _TypeAlias = int
H5_index_t: _TypeAlias = int
H5D_layout_t: _TypeAlias = int
H5D_vds_view_t: _TypeAlias = int
H5D_alloc_time_t: _TypeAlias = int
H5D_space_status_t: _TypeAlias = int
H5D_fill_time_t: _TypeAlias = int
H5D_fill_value_t: _TypeAlias = int
H5F_scope_t: _TypeAlias = int
H5F_close_degree_t: _TypeAlias = int
H5F_fspace_strategy_t: _TypeAlias = int
H5F_libver_t: _TypeAlias = int
H5FD_mem_t: _TypeAlias = int
H5FD_mpio_xfer_t: _TypeAlias = int
H5G_link_t: _TypeAlias = int
H5G_obj_t: _TypeAlias = int
H5G_storage_type_t: _TypeAlias = int
H5I_type_t: _TypeAlias = int
H5L_type_t: _TypeAlias = int
H5O_type_t: _TypeAlias = int
H5R_type_t: _TypeAlias = int
H5S_seloper_t: _TypeAlias = int
H5S_class_t: _TypeAlias = int
H5S_sel_type: _TypeAlias = int
H5T_order_t: _TypeAlias = int
H5T_sign_t: _TypeAlias = int
H5T_norm_t: _TypeAlias = int
H5T_cset_t: _TypeAlias = int
H5T_str_t: _TypeAlias = int
H5T_pad_t: _TypeAlias = int
H5T_class_t: _TypeAlias = int
H5T_direction_t: _TypeAlias = int
H5T_pers_t: _TypeAlias = int
H5T_cmd_t: _TypeAlias = int
H5T_bkg_t: _TypeAlias = int
H5Z_EDC_t: _TypeAlias = int
H5Z_SO_scale_type_t: _TypeAlias = int
H5C_cache_incr_mode: _TypeAlias = int
H5C_cache_flash_incr_mode: _TypeAlias = int
H5C_cache_decr_mode: _TypeAlias = int
hid_t: _TypeAlias = int
hbool_t: _TypeAlias = int
herr_t: _TypeAlias = int
htri_t: _TypeAlias = int
hsize_t: _TypeAlias = int
hssize_t: _TypeAlias = int
haddr_t: _TypeAlias = int
off_t: _TypeAlias = int
H5FD_class_value_t: _TypeAlias = int
H5O_msg_crt_idx_t: _TypeAlias = int
H5Z_filter_t: _TypeAlias = int