# This file was generated by stubgen-pyx v0.2.11 from h5py\h5.pyx

from ._objects import with_phil
from .defs import *


class ByteStringContext:

    def __init__(self):
        ...

    def __bool__(self):
        ...

    def __enter__(self):
        ...

    def __exit__(self, *args):
        ...

class H5PYConfig:

    def __init__(self):
        ...

    @property
    def has_native_complex(self):
        ...

    @property
    def complex_names(self):
        ...

    @complex_names.setter
    def complex_names(self, val):
        ...

    @property
    def bool_names(self):
        ...

    @bool_names.setter
    def bool_names(self, val):
        ...

    @property
    def read_byte_strings(self):
        ...

    @property
    def mpi(self):
        ...

    @property
    def ros3(self):
        ...

    @property
    def direct_vfd(self):
        ...

    @property
    def swmr_min_hdf5_version(self):
        ...

    @property
    def vds_min_hdf5_version(self):
        ...

    @property
    def track_order(self):
        ...

    @track_order.setter
    def track_order(self, val):
        ...

    @property
    def default_file_mode(self):
        ...

    @default_file_mode.setter
    def default_file_mode(self, val):
        ...
ITER_INC = ...
ITER_DEC = ...
ITER_NATIVE = ...
INDEX_NAME = ...
INDEX_CRT_ORDER = ...
HDF5_VERSION_COMPILED_AGAINST = (2, 1, 1)
NUMPY_VERSION_COMPILED_AGAINST = '2.4.6'
CYTHON_VERSION_COMPILED_WITH = '3.2.4'

def get_config() -> H5PYConfig:
    ...

@with_phil
def get_libversion():
    ...