# This file was generated by stubgen-pyx v0.2.10 from h5py\h5.pyx

from ._objects import with_phil
from .defs import *


class ByteStringContext:

    def __init__(self):
        ...

    def __bool__(self):
        ...

    def __enter__(self):
        ...

    def __exit__(self, *args):
        ...

class H5PYConfig:
    """
    Provides runtime access to global library settings.  You retrieve the
    master copy of this object by calling h5py.get_config().

    complex_names (tuple, r/w)
        Settable 2-tuple controlling how complex numbers are saved.
        Defaults to ('r','i').

    bool_names (tuple, r/w)
        Settable 2-tuple controlling the HDF5 enum names used for boolean
        values.  Defaults to ('FALSE', 'TRUE') for values 0 and 1.
    """

    def __init__(self):
        ...

    @property
    def has_native_complex(self):
        """Boolean indicating availability of native HDF5 complex number datatypes."""

    @property
    def complex_names(self):
        """ Settable 2-tuple controlling the field names used for storing
        complex numbers as an HDF5 compound.

        Format is (real_name, imag_name), defaulting to ('r','i').
        """

    @complex_names.setter
    def complex_names(self, val):
        ...

    @property
    def bool_names(self):
        """ Settable 2-tuple controlling HDF5 ENUM names for boolean types.

        Format is (false_name, real_name), defaulting to ('FALSE', 'TRUE').
        """

    @bool_names.setter
    def bool_names(self, val):
        ...

    @property
    def read_byte_strings(self):
        """ Returns a context manager which forces all strings to be returned
        as byte strings. """

    @property
    def mpi(self):
        """ Boolean indicating if Parallel HDF5 is available """

    @property
    def ros3(self):
        """ Boolean indicating if ROS3 VDS is available """

    @property
    def direct_vfd(self):
        """ Boolean indicating if DIRECT VFD is available """

    @property
    def swmr_min_hdf5_version(self):
        """ Tuple indicating the minimum HDF5 version required for SWMR features"""

    @property
    def vds_min_hdf5_version(self):
        """Tuple indicating the minimum HDF5 version required for virtual dataset (VDS) features"""

    @property
    def track_order(self):
        """ Default value for track_order argument of
        File.open()/Group.create_group()/Group.create_dataset() """

    @track_order.setter
    def track_order(self, val):
        ...

    @property
    def default_file_mode(self):
        """Default mode for h5py.File()"""

    @default_file_mode.setter
    def default_file_mode(self, val):
        ...
ITER_INC = ...
ITER_DEC = ...
ITER_NATIVE = ...
INDEX_NAME = ...
INDEX_CRT_ORDER = ...
HDF5_VERSION_COMPILED_AGAINST = (2, 1, 1)
NUMPY_VERSION_COMPILED_AGAINST = '2.4.6'
CYTHON_VERSION_COMPILED_WITH = '3.2.4'

def get_config() -> H5PYConfig:
    """() => H5PYConfig

    Get a reference to the global library configuration object.
    """

@with_phil
def get_libversion():
    """ () => TUPLE (major, minor, release)

    Retrieve the HDF5 library version as a 3-tuple.
    """