# This file was generated by stubgen-pyx v0.2.11 from h5py\h5a.pyx

import cython
from numpy import ndarray

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID
from .h5s import SpaceID
from .h5t import TypeID


class AttrInfo:

    @property
    def corder_valid(self):
        ...

    @property
    def corder(self):
        ...

    @property
    def cset(self):
        ...

    @property
    def data_size(self):
        ...

    def _hash(self):
        ...

class _AttrVisitor:

    def __init__(self, func):
        ...

class AttrID(ObjectID):

    @property
    def name(self):
        ...

    @property
    def shape(self):
        ...

    @property
    def dtype(self):
        ...

    @with_phil
    def read(self, arr: ndarray, mtype: TypeID=None):
        ...

    @with_phil
    def write(self, arr: ndarray, mtype: TypeID=None):
        ...

    @with_phil
    def get_name(self):
        ...

    @with_phil
    def get_space(self):
        ...

    @with_phil
    def get_type(self):
        ...

    @with_phil
    def get_storage_size(self):
        ...

@cython.binding(False)
@with_phil
def create(loc: ObjectID, name: str, tid: TypeID, space: SpaceID, *, obj_name: str='.', lapl: PropID=None):
    ...

@cython.binding(False)
@with_phil
def open(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    ...

@with_phil
def exists(loc: ObjectID, name: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@with_phil
def rename(loc: ObjectID, name: str, new_name: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@cython.binding(False)
@with_phil
def delete(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    ...

@with_phil
def get_num_attrs(loc: ObjectID):
    ...

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', lapl: PropID=None, index_type: int=..., order: int=...):
    ...

@with_phil
def iterate(loc: ObjectID, func: object, index: int=0, *, index_type: int=..., order: int=..., info: bool=0):
    ...