# This file was generated by stubgen-pyx v0.2.12 from h5py\h5a.pyx

from typing import TypeAlias

import cython
import numpy as np
from numpy import ndarray

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID
from .h5s import SpaceID
from .h5t import TypeID


class AttrInfo:

    @property
    def corder_valid(self) -> bool:
        ...

    @property
    def corder(self) -> int:
        ...

    @property
    def cset(self) -> int:
        ...

    @property
    def data_size(self) -> hsize_t:
        ...

    def _hash(self) -> int:
        ...

class _AttrVisitor:

    def __init__(self, func) -> None:
        ...

class AttrID(ObjectID):

    @property
    def name(self) -> bytes:
        ...

    @property
    def shape(self) -> tuple:
        ...

    @property
    def dtype(self) -> _DType:
        ...

    @with_phil
    def read(self, arr: ndarray, mtype: TypeID=None) -> None:
        ...

    @with_phil
    def write(self, arr: ndarray, mtype: TypeID=None) -> None:
        ...

    @with_phil
    def get_name(self) -> bytes:
        ...

    @with_phil
    def get_space(self) -> SpaceID:
        ...

    @with_phil
    def get_type(self) -> TypeID:
        ...

    @with_phil
    def get_storage_size(self) -> hsize_t:
        ...
_DType: TypeAlias = np.dtype[np.generic]

@cython.binding(False)
@with_phil
def create(loc: ObjectID, name: str, tid: TypeID, space: SpaceID, *, obj_name: str='.', lapl: PropID=None):
    ...

@cython.binding(False)
@with_phil
def open(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    ...

@with_phil
def exists(loc: ObjectID, name: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@with_phil
def rename(loc: ObjectID, name: str, new_name: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@cython.binding(False)
@with_phil
def delete(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    ...

@with_phil
def get_num_attrs(loc: ObjectID) -> int:
    ...

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', lapl: PropID=None, index_type: int=..., order: int=...) -> AttrInfo:
    ...

@with_phil
def iterate(loc: ObjectID, func: object, index: int=0, *, index_type: int=..., order: int=..., info: bool=0) -> object:
    ...
