# This file was generated by stubgen-pyx v0.2.10 from h5py\h5a.pyx

"""
Provides access to the low-level HDF5 "H5A" attribute interface.
"""
import cython
from numpy import ndarray

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID
from .h5s import SpaceID
from .h5t import TypeID


class AttrInfo:

    @property
    def corder_valid(self):
        """Indicates if the creation order is valid"""

    @property
    def corder(self):
        """Creation order"""

    @property
    def cset(self):
        """Character set of attribute name (integer typecode from h5t)"""

    @property
    def data_size(self):
        """Size of raw data"""

    def _hash(self):
        ...

class _AttrVisitor:

    def __init__(self, func):
        ...

class AttrID(ObjectID):
    """
    Logical representation of an HDF5 attribute identifier.

    Objects of this class can be used in any HDF5 function call
    which expects an attribute identifier.  Additionally, all ``H5A*``
    functions which always take an attribute instance as the first
    argument are presented as methods of this class.

    * Hashable: No
    * Equality: Identifier comparison
    """

    @property
    def name(self):
        """The attribute's name"""

    @property
    def shape(self):
        """A Numpy-style shape tuple representing the attribute's dataspace"""

    @property
    def dtype(self):
        """A Numpy-stype dtype object representing the attribute's datatype"""

    @with_phil
    def read(self, arr: ndarray, mtype: TypeID=None):
        """(NDARRAY arr, TypeID mtype=None)

        Read the attribute data into the given Numpy array.  Note that the
        Numpy array must have the same shape as the HDF5 attribute, and a
        conversion-compatible datatype.

        The Numpy array must be writable and C-contiguous.  If this is not
        the case, the read will fail with an exception.

        If provided, the HDF5 TypeID mtype will override the array's dtype.
        """

    @with_phil
    def write(self, arr: ndarray, mtype: TypeID=None):
        """(NDARRAY arr)

        Write the contents of a Numpy array to the attribute.  Note that
        the Numpy array must have the same shape as the HDF5 attribute, and
        a conversion-compatible datatype.

        The Numpy array must be C-contiguous.  If this is not the case,
        the write will fail with an exception.
        """

    @with_phil
    def get_name(self):
        """() => STRING name

        Determine the name of this attribute.
        """

    @with_phil
    def get_space(self):
        """() => SpaceID

        Create and return a copy of the attribute's dataspace.
        """

    @with_phil
    def get_type(self):
        """() => TypeID

        Create and return a copy of the attribute's datatype.
        """

    @with_phil
    def get_storage_size(self):
        """() => INT

        Get the amount of storage required for this attribute.
        """

@cython.binding(False)
@with_phil
def create(loc: ObjectID, name: str, tid: TypeID, space: SpaceID, *, obj_name: str='.', lapl: PropID=None):
    """(ObjectID loc, STRING name, TypeID tid, SpaceID space, **kwds) => AttrID

    Create a new attribute, attached to an existing object.

    STRING obj_name (".")
        Attach attribute to this group member instead

    PropID lapl
        Link access property list for obj_name
    """

@cython.binding(False)
@with_phil
def open(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    """(ObjectID loc, STRING name=, INT index=, **kwds) => AttrID

    Open an attribute attached to an existing object.  You must specify
    exactly one of either name or idx.  Keywords are:

    STRING obj_name (".")
        Attribute is attached to this group member

    PropID lapl (None)
        Link access property list for obj_name

    INT index_type (h5.INDEX_NAME)

    INT order (h5.ITER_INC)

    """

@with_phil
def exists(loc: ObjectID, name: str, *, obj_name: str='.', lapl: PropID=None):
    """(ObjectID loc, STRING name, **kwds) => BOOL

    Determine if an attribute is attached to this object.  Keywords:

    STRING obj_name (".")
        Look for attributes attached to this group member

    PropID lapl (None):
        Link access property list for obj_name
    """

@with_phil
def rename(loc: ObjectID, name: str, new_name: str, *, obj_name: str='.', lapl: PropID=None):
    """(ObjectID loc, STRING name, STRING new_name, **kwds)

    Rename an attribute.  Keywords:

    STRING obj_name (".")
        Attribute is attached to this group member

    PropID lapl (None)
        Link access property list for obj_name
    """

@cython.binding(False)
@with_phil
def delete(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    """(ObjectID loc, STRING name=, INT index=, **kwds)

    Remove an attribute from an object.  Specify exactly one of "name"
    or "index". Keyword-only arguments:

    STRING obj_name (".")
        Attribute is attached to this group member

    PropID lapl (None)
        Link access property list for obj_name

    INT index_type (h5.INDEX_NAME)

    INT order (h5.ITER_INC)
    """

@with_phil
def get_num_attrs(loc: ObjectID):
    """(ObjectID loc) => INT

    Determine the number of attributes attached to an HDF5 object.
    """

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', lapl: PropID=None, index_type: int=..., order: int=...):
    """(ObjectID loc, STRING name=, INT index=, **kwds) => AttrInfo

    Get information about an attribute, in one of two ways:

    1. If you have the attribute identifier, just pass it in
    2. If you have the parent object, supply it and exactly one of
       either name or index.

    STRING obj_name (".")
        Use this group member instead

    PropID lapl (None)
        Link access property list for obj_name

    INT index_type (h5.INDEX_NAME)
        Which index to use

    INT order (h5.ITER_INC)
        What order the index is in
    """

@with_phil
def iterate(loc: ObjectID, func: object, index: int=0, *, index_type: int=..., order: int=..., info: bool=0):
    """(ObjectID loc, CALLABLE func, INT index=0, **kwds) => <Return value from func>

    Iterate a callable (function, method or callable object) over the
    attributes attached to this object.  You callable should have the
    signature::

        func(STRING name) => Result

    or if the keyword argument "info" is True::

        func(STRING name, AttrInfo info) => Result

    Returning None continues iteration; returning anything else aborts
    iteration and returns that value.  Keywords:

    BOOL info (False)
        Callback is func(STRING name, AttrInfo info), not func(STRING name)

    INT index_type (h5.INDEX_NAME)
        Which index to use

    INT order (h5.ITER_INC)
        Index order to use
    """