# This file was generated by stubgen-pyx v0.2.11 from h5py\h5ac.pyx

from .defs import *


class CacheConfig:

    def __cinit__(self):
        ...

    @property
    def version(self):
        ...

    @version.setter
    def version(self, val: int):
        ...

    @property
    def rpt_fcn_enabled(self):
        ...

    @rpt_fcn_enabled.setter
    def rpt_fcn_enabled(self, val: hbool_t):
        ...

    @property
    def evictions_enabled(self):
        ...

    @evictions_enabled.setter
    def evictions_enabled(self, val: hbool_t):
        ...

    @property
    def set_initial_size(self):
        ...

    @set_initial_size.setter
    def set_initial_size(self, val: hbool_t):
        ...

    @property
    def initial_size(self):
        ...

    @initial_size.setter
    def initial_size(self, val: int):
        ...

    @property
    def min_clean_fraction(self):
        ...

    @min_clean_fraction.setter
    def min_clean_fraction(self, val: float):
        ...

    @property
    def max_size(self):
        ...

    @max_size.setter
    def max_size(self, val: int):
        ...

    @property
    def min_size(self):
        ...

    @min_size.setter
    def min_size(self, val: int):
        ...

    @property
    def epoch_length(self):
        ...

    @epoch_length.setter
    def epoch_length(self, val: int):
        ...

    @property
    def incr_mode(self):
        ...

    @incr_mode.setter
    def incr_mode(self, val: H5C_cache_incr_mode):
        ...

    @property
    def lower_hr_threshold(self):
        ...

    @lower_hr_threshold.setter
    def lower_hr_threshold(self, val: float):
        ...

    @property
    def increment(self):
        ...

    @increment.setter
    def increment(self, val: float):
        ...

    @property
    def apply_max_increment(self):
        ...

    @apply_max_increment.setter
    def apply_max_increment(self, val: hbool_t):
        ...

    @property
    def max_increment(self):
        ...

    @max_increment.setter
    def max_increment(self, val: int):
        ...

    @property
    def flash_incr_mode(self):
        ...

    @flash_incr_mode.setter
    def flash_incr_mode(self, val: H5C_cache_flash_incr_mode):
        ...

    @property
    def flash_multiple(self):
        ...

    @flash_multiple.setter
    def flash_multiple(self, val: float):
        ...

    @property
    def flash_threshold(self):
        ...

    @flash_threshold.setter
    def flash_threshold(self, val: float):
        ...

    @property
    def decr_mode(self):
        ...

    @decr_mode.setter
    def decr_mode(self, val: H5C_cache_decr_mode):
        ...

    @property
    def upper_hr_threshold(self):
        ...

    @upper_hr_threshold.setter
    def upper_hr_threshold(self, val: float):
        ...

    @property
    def decrements(self):
        ...

    @decrements.setter
    def decrements(self, val: float):
        ...

    @property
    def apply_max_decrement(self):
        ...

    @apply_max_decrement.setter
    def apply_max_decrement(self, val: hbool_t):
        ...

    @property
    def max_decrement(self):
        ...

    @max_decrement.setter
    def max_decrement(self, val: int):
        ...

    @property
    def epochs_before_eviction(self):
        ...

    @epochs_before_eviction.setter
    def epochs_before_eviction(self, val: int):
        ...

    @property
    def apply_empty_reserve(self):
        ...

    @apply_empty_reserve.setter
    def apply_empty_reserve(self, val: hbool_t):
        ...

    @property
    def empty_reserve(self):
        ...

    @empty_reserve.setter
    def empty_reserve(self, val: float):
        ...

    @property
    def dirty_bytes_threshold(self):
        ...

    @dirty_bytes_threshold.setter
    def dirty_bytes_threshold(self, val: int):
        ...