# This file was generated by stubgen-pyx v0.2.11 from h5py\h5ds.pyx

from ._objects import with_phil
from .defs import *
from .h5d import DatasetID


class _DimensionScaleVisitor:

    def __init__(self, func):
        ...

@with_phil
def set_scale(dset: DatasetID, dimname: str=''):
    ...

@with_phil
def is_scale(dset: DatasetID):
    ...

@with_phil
def attach_scale(dset: DatasetID, dscale: DatasetID, idx: int):
    ...

@with_phil
def is_attached(dset: DatasetID, dscale: DatasetID, idx: int):
    ...

@with_phil
def detach_scale(dset: DatasetID, dscale: DatasetID, idx: int):
    ...

@with_phil
def get_num_scales(dset: DatasetID, dim: int):
    ...

@with_phil
def set_label(dset: DatasetID, idx: int, label: str):
    ...

@with_phil
def get_label(dset: DatasetID, idx: int):
    ...

@with_phil
def get_scale_name(dscale: DatasetID):
    ...

@with_phil
def iterate(dset: DatasetID, dim: int, func: object, startidx: int=0):
    ...