# This file was generated by stubgen-pyx v0.2.10 from h5py\h5ds.pyx

"""
Low-level HDF5 "H5DS" Dimension Scale interface.
"""
from ._objects import with_phil
from .defs import *
from .h5d import DatasetID


class _DimensionScaleVisitor:

    def __init__(self, func):
        ...

@with_phil
def set_scale(dset: DatasetID, dimname: str=''):
    """(DatasetID dset, STRING dimname)

    Convert dataset dset to a dimension scale, with optional name dimname.
    """

@with_phil
def is_scale(dset: DatasetID):
    """(DatasetID dset) => BOOL

    Determines whether dset is a dimension scale.
    """

@with_phil
def attach_scale(dset: DatasetID, dscale: DatasetID, idx: int):
    """(DatasetID dset, DatasetID dscale, UINT idx)

    Attach Dimension Scale dscale to Dimension idx of Dataset dset.
    """

@with_phil
def is_attached(dset: DatasetID, dscale: DatasetID, idx: int):
    """(DatasetID dset, DatasetID dscale, UINT idx) => BOOL

    Report if Dimension Scale dscale is currently attached to Dimension
    idx of Dataset dset.
    """

@with_phil
def detach_scale(dset: DatasetID, dscale: DatasetID, idx: int):
    """(DatasetID dset, DatasetID dscale, UINT idx)

    Detach Dimension Scale dscale from the Dimension idx of Dataset dset.
    """

@with_phil
def get_num_scales(dset: DatasetID, dim: int):
    """(DatasetID dset, UINT dim) => INT number_of_scales

    Determines how many Dimension Scales are attached to Dimension dim
    of Dataset dset.
    """

@with_phil
def set_label(dset: DatasetID, idx: int, label: str):
    """(DatasetID dset, UINT idx, STRING label)

    Set label for the Dimension idx of Dataset dset to the value label.
    """

@with_phil
def get_label(dset: DatasetID, idx: int):
    """(DatasetID dset, UINT idx) => STRING name_of_label

    Read the label for Dimension idx of Dataset dset into buffer label.
    """

@with_phil
def get_scale_name(dscale: DatasetID):
    """(DatasetID dscale) => STRING name_of_scale

    Retrieves name of Dimension Scale dscale.
    """

@with_phil
def iterate(dset: DatasetID, dim: int, func: object, startidx: int=0):
    """ (DatasetID loc, UINT dim, CALLABLE func, UINT startidx=0)
    => Return value from func

    Iterate a callable (function, method or callable object) over the
    members of a group.  Your callable should have the signature::

        func(STRING name) => Result

    Returning None continues iteration; returning anything else aborts
    iteration and returns that value. Keywords:
    """