# This file was generated by stubgen-pyx v0.2.10 from h5py\h5f.pyx

"""
Low-level operations on HDF5 file objects.
"""
from collections import namedtuple

from ._objects import ObjectID, with_phil
from .defs import *
from .h5ac import CacheConfig
from .h5g import GroupID
from .h5p import PropFAID, PropFCID


class FileID(GroupID):
    """
    Represents an HDF5 file identifier.

    These objects wrap a small portion of the H5F interface; all the
    H5F functions which can take arbitrary objects in addition to
    file identifiers are provided as functions in the h5f module.

    Properties:

    * name:   File name on disk

    Behavior:

    * Hashable: Yes, unique to the file (but not the access mode)
    * Equality: Hash comparison
    """

    @property
    def name(self):
        """ File name on disk (according to h5f.get_name()) """

    @with_phil
    def close(self):
        """()

        Terminate access through this identifier.  Note that depending on
        what property list settings were used to open the file, the
        physical file might not be closed until all remaining open
        identifiers are freed.
        """

    @with_phil
    def _close_open_objects(self, types: int):
        ...

    @with_phil
    def reopen(self):
        """() => FileID

        Retrieve another identifier for a file (which must still be open).
        The new identifier is guaranteed to neither be mounted nor contain
        a mounted file.
        """

    @with_phil
    def get_filesize(self):
        """() => LONG size

        Determine the total size (in bytes) of the HDF5 file,
        including any user block.
        """

    @with_phil
    def get_create_plist(self):
        """() => PropFCID

        Retrieve a copy of the file creation property list used to
        create this file.
        """

    @with_phil
    def get_access_plist(self):
        """() => PropFAID

        Retrieve a copy of the file access property list which manages access
        to this file.
        """

    @with_phil
    def get_freespace(self):
        """() => LONG freespace

        Determine the amount of free space in this file.  Note that this
        only tracks free space until the file is closed.
        """

    @with_phil
    def get_intent(self):
        """ () => INT

        Determine the file's write intent, either of:
        - H5F_ACC_RDONLY
        - H5F_ACC_RDWR
        """

    @with_phil
    def get_vfd_handle(self, fapl=None):
        """ (PropFAID) => INT

        Retrieve the file handle used by the virtual file driver.

        This may not be supported for all file drivers, and the meaning of the
        return value may depend on the file driver.

        The 'family' and 'multi' drivers access multiple files, and a file
        access property list (fapl) can be used to indicate which to access,
        with H5Pset_family_offset or H5Pset_multi_type.
        """

    @with_phil
    def get_file_image(self):
        """ () => BYTES

        Retrieves a copy of the image of an existing, open file.
        """

    @with_phil
    def get_mdc_hit_rate(self):
        """() => DOUBLE

        Retrieve the cache hit rate

        """

    @with_phil
    def get_mdc_size(self):
        """() => (max_size, min_clean_size, cur_size, cur_num_entries) [SIZE_T, SIZE_T, SIZE_T, INT]

        Obtain current metadata cache size data for specified file.

        """

    @with_phil
    def reset_mdc_hit_rate_stats(self):
        """no return

        rests the hit-rate statistics

        """

    @with_phil
    def get_mdc_config(self):
        """() => CacheConfig
        Returns an object that stores all the information about the meta-data cache
        configuration. This config is created for every file in-memory with the default
        cache config values, it is not saved to the hdf5 file.
        """

    @with_phil
    def set_mdc_config(self, config: CacheConfig):
        """(CacheConfig) => None
        Sets the meta-data cache configuration for a file. This config is created for every file
        in-memory with the default config values, it is not saved to the hdf5 file. Any change to
        the configuration lives until the hdf5 file is closed.
        """

    @with_phil
    def start_swmr_write(self):
        """ no return

        Enables SWMR writing mode for a file.

        This function will activate SWMR writing mode for a file associated
        with file_id. This routine will prepare and ensure the file is safe
        for SWMR writing as follows:

            * Check that the file is opened with write access (H5F_ACC_RDWR).
            * Check that the file is opened with the latest library format
              to ensure data structures with check-summed metadata are used.
            * Check that the file is not already marked in SWMR writing mode.
            * Enable reading retries for check-summed metadata to remedy
              possible checksum failures from reading inconsistent metadata
              on a system that is not atomic.
            * Turn off usage of the libraryâ€™s accumulator to avoid possible
              ordering problem on a system that is not atomic.
            * Perform a flush of the fileâ€™s data buffers and metadata to set
              a consistent state for starting SWMR write operations.

        Library objects are groups, datasets, and committed datatypes. For
        the current implementation, groups and datasets can remain open when
        activating SWMR writing mode, but not committed datatypes. Attributes
        attached to objects cannot remain open.

        Feature requires: 1.9.178 HDF5
        """

    @with_phil
    def reset_page_buffering_stats(self):
        """ ()

        Reset page buffer statistics for the file.
        """

    @with_phil
    def get_page_buffering_stats(self):
        """ () -> NAMEDTUPLE PageBufStats(NAMEDTUPLE meta=PageStats, NAMEDTUPLE raw=PageStats)

        Retrieve page buffering statistics for the file as the number of
        metadata and raw data accesses, hits, misses, evictions, and
        accesses that bypass the page buffer (bypasses).
        """

    @with_phil
    def __iter__(self):
        """ Return an iterator over the names of group members. """

    @with_phil
    def __reversed__(self):
        """ Return an iterator over group member names in reverse order. """
ACC_TRUNC = ...
ACC_EXCL = ...
ACC_RDWR = ...
ACC_RDONLY = ...
ACC_SWMR_WRITE = ...
ACC_SWMR_READ = ...
SCOPE_LOCAL = ...
SCOPE_GLOBAL = ...
CLOSE_DEFAULT = ...
CLOSE_WEAK = ...
CLOSE_SEMI = ...
CLOSE_STRONG = ...
OBJ_FILE = ...
OBJ_DATASET = ...
OBJ_GROUP = ...
OBJ_DATATYPE = ...
OBJ_ATTR = ...
OBJ_ALL = ...
OBJ_LOCAL = ...
UNLIMITED = ...
LIBVER_EARLIEST = ...
LIBVER_LATEST = ...
LIBVER_V18 = ...
LIBVER_V110 = ...
LIBVER_V112 = ...
LIBVER_V114 = ...
LIBVER_V200 = ...
FILE_IMAGE_OPEN_RW = ...
FSPACE_STRATEGY_FSM_AGGR = ...
FSPACE_STRATEGY_PAGE = ...
FSPACE_STRATEGY_AGGR = ...
FSPACE_STRATEGY_NONE = ...
PageBufStats = namedtuple('PageBufferStats', ['meta', 'raw'])
PageStats = namedtuple('PageStats', ['accesses', 'hits', 'misses', 'evictions', 'bypasses'])

@with_phil
def open(name: str, flags: int=..., fapl: PropFAID=None):
    """(STRING name, UINT flags=ACC_RDWR, PropFAID fapl=None) => FileID

    Open an existing HDF5 file.  Keyword "flags" may be:

    ACC_RDWR
        Open in read-write mode

    ACC_RDONLY
        Open in readonly mode

    Keyword fapl may be a file access property list.
    """

@with_phil
def create(name: str, flags: int=..., fcpl: PropFCID=None, fapl: PropFAID=None):
    """(STRING name, INT flags=ACC_TRUNC, PropFCID fcpl=None,
    PropFAID fapl=None) => FileID

    Create a new HDF5 file.  Keyword "flags" may be:

    ACC_TRUNC
        Truncate an existing file, discarding its data

    ACC_EXCL
        Fail if a conflicting file exists

    To keep the behavior in line with that of Python's built-in functions,
    the default is ACC_TRUNC.  Be careful!
    """

@with_phil
def open_file_image(image, flags=0):
    """(STRING image, INT flags=0) => FileID

    Load a new HDF5 file into memory.  Keyword "flags" may be:

    FILE_IMAGE_OPEN_RW
        Specifies opening the file image in read/write mode.
    """

@with_phil
def flush(obj: ObjectID, scope: int=...):
    """(ObjectID obj, INT scope=SCOPE_LOCAL)

    Tell the HDF5 library to flush file buffers to disk.  "obj" may
    be the file identifier, or the identifier of any object residing in
    the file.  Keyword "scope" may be:

    SCOPE_LOCAL
        Flush only the given file

    SCOPE_GLOBAL
        Flush the entire virtual file
    """

@with_phil
def is_hdf5(name: str):
    """(STRING name) => BOOL

    Determine if a given file is an HDF5 file.  Note this raises an
    exception if the file doesn't exist.
    """

@with_phil
def mount(loc: ObjectID, name: str, fid: FileID):
    """(ObjectID loc, STRING name, FileID fid)

    Mount an open file on the group "name" under group loc_id.  Note that
    "name" must already exist.
    """

@with_phil
def unmount(loc: ObjectID, name: str):
    """(ObjectID loc, STRING name)

    Unmount a file, mounted at "name" under group loc_id.
    """

@with_phil
def get_name(obj: ObjectID):
    """(ObjectID obj) => STRING

    Determine the name of the file in which the specified object resides.
    """

@with_phil
def get_obj_count(where: object=OBJ_ALL, types: int=...):
    """(OBJECT where=OBJ_ALL, types=OBJ_ALL) => INT

    Get the number of open objects.

    where
        Either a FileID instance representing an HDF5 file, or the
        special constant OBJ_ALL, to count objects in all files.

    type
        Specify what kinds of object to include.  May be one of OBJ*,
        or any bitwise combination (e.g. ``OBJ_FILE | OBJ_ATTR``).

        The special value OBJ_ALL matches all object types, and
        OBJ_LOCAL will only match objects opened through a specific
        identifier.
    """

@with_phil
def get_obj_ids(where: object=OBJ_ALL, types: int=...):
    """(OBJECT where=OBJ_ALL, types=OBJ_ALL) => LIST

    Get a list of identifier instances for open objects.

    where
        Either a FileID instance representing an HDF5 file, or the
        special constant OBJ_ALL, to list objects in all files.

    type
        Specify what kinds of object to include.  May be one of OBJ*,
        or any bitwise combination (e.g. ``OBJ_FILE | OBJ_ATTR``).

        The special value OBJ_ALL matches all object types, and
        OBJ_LOCAL will only match objects opened through a specific
        identifier.
    """