ACC_TRUNC: int
ACC_EXCL: int
ACC_RDWR: int
ACC_RDONLY: int
ACC_SWMR_WRITE: int
ACC_SWMR_READ: int

SCOPE_LOCAL: int
SCOPE_GLOBAL: int

CLOSE_DEFAULT: int
CLOSE_WEAK: int
CLOSE_SEMI: int
CLOSE_STRONG: int

OBJ_FILE: int
OBJ_DATASET: int
OBJ_GROUP: int
OBJ_DATATYPE: int
OBJ_ATTR: int
OBJ_ALL: int
OBJ_LOCAL: int
UNLIMITED: int

LIBVER_EARLIEST: int
LIBVER_LATEST: int
LIBVER_V18: int
LIBVER_V110: int
LIBVER_V112: int
LIBVER_V114: int

FILE_IMAGE_OPEN_RW: int

FSPACE_STRATEGY_FSM_AGGR: int
FSPACE_STRATEGY_PAGE: int
FSPACE_STRATEGY_AGGR: int
FSPACE_STRATEGY_NONE: int
