# This file was generated by stubgen-pyx v0.2.10 from h5py\h5g.pyx

"""
Low-level HDF5 "H5G" group interface.
"""
import sys

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID


class GroupStat:
    """Represents the H5G_stat_t structure containing group member info.

    Fields (read-only):

    * fileno:   2-tuple uniquely identifying the current file
    * objno:    2-tuple uniquely identifying this object
    * nlink:    Number of hard links to this object
    * mtime:    Modification time of this object
    * linklen:  Length of the symbolic link name, or 0 if not a link.

    "Uniquely identifying" means unique among currently open files,
    not universally unique.

    * Hashable: Yes
    * Equality: Yes
    """

    @property
    def fileno(self):
        ...

    @property
    def objno(self):
        ...

    @property
    def nlink(self):
        ...

    @property
    def type(self):
        ...

    @property
    def mtime(self):
        ...

    @property
    def linklen(self):
        ...

    def _hash(self):
        ...

class GroupIter:
    """
    Iterator over the names of group members.  After this iterator is
    exhausted, it releases its reference to the group ID.
    """

    def __init__(self, grp: GroupID, reversed: bool=False):
        ...

    def __iter__(self):
        ...

    def __next__(self):
        ...

class _GroupVisitor:

    def __init__(self, func):
        ...

class GroupID(ObjectID):
    """
    Represents an HDF5 group identifier

    Python extensions:

    __contains__
        Test for group member ("if name in grpid")

    __iter__
        Get an iterator over member names

    __len__
        Number of members in this group; len(grpid) = N

    The attribute "links" contains a proxy object
    providing access to the H5L family of routines.  See the docs
    for h5py.h5l.LinkProxy for more information.

    * Hashable: Yes, unless anonymous
    * Equality: True HDF5 identity unless anonymous
    """

    def __init__(self, id_: hid_t):
        ...

    @with_phil
    def link(self, current_name: str, new_name: str, link_type: int=..., remote: GroupID=None):
        """(STRING current_name, STRING new_name, INT link_type=LINK_HARD,
        GroupID remote=None)

        Create a new hard or soft link.  current_name identifies
        the link target (object the link will point to).  The new link is
        identified by new_name and (optionally) another group "remote".

        Link types are:

        LINK_HARD
            Hard link to existing object (default)

        LINK_SOFT
            Symbolic link; link target need not exist.
        """

    @with_phil
    def unlink(self, name: str):
        """(STRING name)

        Remove a link to an object from this group.
        """

    @with_phil
    def move(self, current_name: str, new_name: str, remote: GroupID=None):
        """(STRING current_name, STRING new_name, GroupID remote=None)

        Relink an object.  current_name identifies the object.
        new_name and (optionally) another group "remote" determine
        where it should be moved.
        """

    @with_phil
    def get_num_objs(self):
        """() => INT number_of_objects

        Get the number of objects directly attached to a given group.
        """

    @with_phil
    def get_objname_by_idx(self, idx: hsize_t):
        """(INT idx) => STRING

        Get the name of a group member given its zero-based index.
        """

    @with_phil
    def get_objtype_by_idx(self, idx: hsize_t):
        """(INT idx) => INT object_type_code

        Get the type of an object attached to a group, given its zero-based
        index.  Possible return values are:

        - LINK
        - GROUP
        - DATASET
        - TYPE
        """

    @with_phil
    def get_linkval(self, name: str):
        """(STRING name) => STRING link_value

        Retrieve the value (target name) of a symbolic link.
        Limited to 2048 characters on Windows.
        """

    @with_phil
    def get_create_plist(self):
        """() => PropGCID

        Retrieve a copy of the group creation property list used to
        create this group.
        """

    @with_phil
    def set_comment(self, name: str, comment: str):
        """(STRING name, STRING comment)

        Set the comment on a group member.
        """

    @with_phil
    def get_comment(self, name: str):
        """(STRING name) => STRING comment

        Retrieve the comment for a group member.
        """

    def __contains__(self, name):
        """(STRING name)

        Determine if a group member of the given name is present
        """

    def __iter__(self):
        """ Return an iterator over the names of group members. """

    def __reversed__(self):
        """ Return an iterator over group member names in reverse order. """

    def __len__(self):
        """ Number of group members """
_IS_WINDOWS = sys.platform.startswith('win')
UNKNOWN = ...
LINK = ...
GROUP = ...
DATASET = ...
TYPE = ...
LINK_ERROR = ...
LINK_HARD = ...
LINK_SOFT = ...

@with_phil
def open(loc: ObjectID, name: str):
    """(ObjectID loc, STRING name) => GroupID

    Open an existing HDF5 group, attached to some other group.
    """

@with_phil
def create(loc: ObjectID, name: object, lcpl: PropID=None, gcpl: PropID=None):
    """(ObjectID loc, STRING name or None, PropLCID lcpl=None,
        PropGCID gcpl=None)
    => GroupID

    Create a new group, under a given parent group.  If name is None,
    an anonymous group will be created in the file.
    """

@with_phil
def iterate(loc: GroupID, func: object, startidx: int=0, *, obj_name: str='.'):
    """ (GroupID loc, CALLABLE func, UINT startidx=0, **kwds)
    => Return value from func

    Iterate a callable (function, method or callable object) over the
    members of a group.  Your callable should have the signature::

        func(STRING name) => Result

    Returning None continues iteration; returning anything else aborts
    iteration and returns that value. Keywords:

    STRING obj_name (".")
        Iterate over this subgroup instead
    """

@with_phil
def get_objinfo(obj: ObjectID, name: object=b'.', follow_link: int=1):
    """(ObjectID obj, STRING name='.', BOOL follow_link=True) => GroupStat object

    Obtain information about a named object.  If "name" is provided,
    "obj" is taken to be a GroupID object containing the target.
    The return value is a GroupStat object; see that class's docstring
    for a description of its attributes.

    If follow_link is True (default) and the object is a symbolic link,
    the information returned describes its target.  Otherwise the
    information describes the link itself.
    """

@with_phil
def _path_valid(grp: GroupID, path: object, lapl: PropID=None):
    """ Determine if *path* points to an object in the file.

    If *path* represents an external or soft link, the link's validity is not
    checked.
    """