# This file was generated by stubgen-pyx v0.2.11 from h5py\h5g.pyx

import sys

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID


class GroupStat:

    @property
    def fileno(self):
        ...

    @property
    def objno(self):
        ...

    @property
    def nlink(self):
        ...

    @property
    def type(self):
        ...

    @property
    def mtime(self):
        ...

    @property
    def linklen(self):
        ...

    def _hash(self):
        ...

class GroupIter:

    def __init__(self, grp: GroupID, reversed: bool=False):
        ...

    def __iter__(self):
        ...

    def __next__(self):
        ...

class _GroupVisitor:

    def __init__(self, func):
        ...

class GroupID(ObjectID):

    def __init__(self, id_: hid_t):
        ...

    @with_phil
    def link(self, current_name: str, new_name: str, link_type: int=..., remote: GroupID=None):
        ...

    @with_phil
    def unlink(self, name: str):
        ...

    @with_phil
    def move(self, current_name: str, new_name: str, remote: GroupID=None):
        ...

    @with_phil
    def get_num_objs(self):
        ...

    @with_phil
    def get_objname_by_idx(self, idx: hsize_t):
        ...

    @with_phil
    def get_objtype_by_idx(self, idx: hsize_t):
        ...

    @with_phil
    def get_linkval(self, name: str):
        ...

    @with_phil
    def get_create_plist(self):
        ...

    @with_phil
    def set_comment(self, name: str, comment: str):
        ...

    @with_phil
    def get_comment(self, name: str):
        ...

    def __contains__(self, name):
        ...

    def __iter__(self):
        ...

    def __reversed__(self):
        ...

    def __len__(self):
        ...
_IS_WINDOWS = sys.platform.startswith('win')
UNKNOWN = ...
LINK = ...
GROUP = ...
DATASET = ...
TYPE = ...
LINK_ERROR = ...
LINK_HARD = ...
LINK_SOFT = ...

@with_phil
def open(loc: ObjectID, name: str):
    ...

@with_phil
def create(loc: ObjectID, name: object, lcpl: PropID=None, gcpl: PropID=None):
    ...

@with_phil
def iterate(loc: GroupID, func: object, startidx: int=0, *, obj_name: str='.'):
    ...

@with_phil
def get_objinfo(obj: ObjectID, name: object=b'.', follow_link: int=1):
    ...

@with_phil
def _path_valid(grp: GroupID, path: object, lapl: PropID=None):
    ...