# This file was generated by stubgen-pyx v0.2.12 from h5py\h5g.pyx

import sys
from typing import Callable, Iterator

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID


class GroupStat:

    @property
    def fileno(self) -> tuple[int, int]:
        ...

    @property
    def objno(self) -> tuple[int, int]:
        ...

    @property
    def nlink(self) -> int:
        ...

    @property
    def type(self) -> H5O_type_t:
        ...

    @property
    def mtime(self) -> int:
        ...

    @property
    def linklen(self) -> int:
        ...

    def _hash(self) -> int:
        ...

class GroupIter:

    def __init__(self, grp: GroupID, reversed: bool=False) -> None:
        ...

    def __iter__(self) -> Iterator:
        ...

    def __next__(self) -> object:
        ...

class _GroupVisitor:

    def __init__(self, func: Callable) -> None:
        ...

class GroupID(ObjectID):

    def __init__(self, id_: hid_t) -> None:
        ...

    @with_phil
    def link(self, current_name: str, new_name: str, link_type: int=..., remote: GroupID=None) -> None:
        ...

    @with_phil
    def unlink(self, name: str) -> None:
        ...

    @with_phil
    def move(self, current_name: str, new_name: str, remote: GroupID=None) -> None:
        ...

    @with_phil
    def get_num_objs(self) -> hsize_t:
        ...

    @with_phil
    def get_objname_by_idx(self, idx: hsize_t) -> bytes:
        ...

    @with_phil
    def get_objtype_by_idx(self, idx: hsize_t) -> int:
        ...

    @with_phil
    def get_linkval(self, name: str) -> bytes:
        ...

    @with_phil
    def get_create_plist(self) -> PropID:
        ...

    @with_phil
    def set_comment(self, name: str, comment: str) -> None:
        ...

    @with_phil
    def get_comment(self, name: str) -> bytes:
        ...

    def __contains__(self, name) -> bool:
        ...

    def __iter__(self) -> GroupIter:
        ...

    def __reversed__(self) -> GroupIter:
        ...

    def __len__(self) -> hsize_t:
        ...
_IS_WINDOWS: bool = sys.platform.startswith('win')
UNKNOWN: int = ...
LINK: int = ...
GROUP: int = ...
DATASET: int = ...
TYPE: int = ...
LINK_ERROR: int = ...
LINK_HARD: int = ...
LINK_SOFT: int = ...

@with_phil
def open(loc: ObjectID, name: str) -> GroupID:
    ...

@with_phil
def create(loc: ObjectID, name: object, lcpl: PropID=None, gcpl: PropID=None) -> GroupID:
    ...

@with_phil
def iterate(loc: GroupID, func: object, startidx: int=0, *, obj_name: str='.') -> object:
    ...

@with_phil
def get_objinfo(obj: ObjectID, name: object=b'.', follow_link: int=1) -> GroupStat:
    ...

@with_phil
def _path_valid(grp: GroupID, path: object, lapl: PropID=None) -> bool:
    ...
