# This file was generated by stubgen-pyx v0.2.10 from h5py\h5i.pyx

"""
Identifier interface for object inspection.
"""
from ._objects import ObjectID, with_phil
from .defs import *

INVALID_HID = ...
BADID = ...
FILE = ...
GROUP = ...
DATASPACE = ...
DATASET = ...
ATTR = ...
GENPROP_CLS = ...
GENPROP_LST = ...
DATATYPE = ...

def wrap_identifier(ident: hid_t) -> ObjectID:
    ...

@with_phil
def get_type(obj: ObjectID):
    """ (ObjectID obj) => INT type_code

    Determine the HDF5 typecode of an arbitrary HDF5 object.  The return
    value is always one of the type constants defined in this module; if
    the ID is invalid, BADID is returned.
    """

@with_phil
def get_name(obj: ObjectID):
    """ (ObjectID obj) => STRING name, or None

    Determine (a) name of an HDF5 object.  Because an object has as many
    names as there are hard links to it, this may not be unique.

    If the identifier is invalid or is not associated with a name
    (in the case of transient datatypes, dataspaces, etc), returns None.

    For some reason, this does not work on dereferenced objects.
    """

@with_phil
def get_file_id(obj: ObjectID):
    """ (ObjectID obj) => FileID

    Obtain an identifier for the file in which this object resides.
    """

@with_phil
def inc_ref(obj: ObjectID):
    """ (ObjectID obj)

    Increment the reference count for the given object.

    This function is provided for debugging only.  Reference counting
    is automatically synchronized with Python, and you can easily break
    ObjectID instances by abusing this function.
    """

@with_phil
def get_ref(obj: ObjectID):
    """ (ObjectID obj) => INT

    Retrieve the reference count for the given object.
    """

@with_phil
def dec_ref(obj: ObjectID):
    """ (ObjectID obj)

    Decrement the reference count for the given object.

    This function is provided for debugging only.  Reference counting
    is automatically synchronized with Python, and you can easily break
    ObjectID instances by abusing this function.
    """