# This file was generated by stubgen-pyx v0.2.11 from h5py\h5l.pyx

from ._objects import with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class LinkInfo:

    @property
    def type(self):
        ...

    @property
    def corder_valid(self):
        ...

    @property
    def corder(self):
        ...

    @property
    def cset(self):
        ...

    @property
    def u(self):
        ...

class _LinkVisitor:

    def __init__(self, func):
        ...

class LinkProxy:

    def __init__(self, id_: hid_t):
        ...

    def __richcmp__(self, other: object, how: int):
        ...

    def __hash__(self):
        ...

    @with_phil
    def create_hard(self, new_name: str, cur_loc: GroupID, cur_name: str, lcpl: PropID=None, lapl: PropID=None):
        ...

    @with_phil
    def create_soft(self, new_name: str, target: str, lcpl: PropID=None, lapl: PropID=None):
        ...

    @with_phil
    def create_external(self, link_name: str, file_name: str, obj_name: str, lcpl: PropID=None, lapl: PropID=None):
        ...

    @with_phil
    def get_val(self, name: str, lapl: PropID=None):
        ...

    @with_phil
    def move(self, src_name: str, dst_loc: GroupID, dst_name: str, lcpl: PropID=None, lapl: PropID=None):
        ...

    @with_phil
    def exists(self, name: str, lapl: PropID=None):
        ...

    @with_phil
    def get_info(self, name: str, index: int=-1, *, lapl: PropID=None):
        ...

    @with_phil
    def visit(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0):
        ...

    @with_phil
    def iterate(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0, idx: hsize_t=0):
        ...
TYPE_HARD = ...
TYPE_SOFT = ...
TYPE_EXTERNAL = ...