# This file was generated by stubgen-pyx v0.2.12 from h5py\h5l.pyx

from ._objects import with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class LinkInfo:

    @property
    def type(self) -> int:
        ...

    @property
    def corder_valid(self) -> bool:
        ...

    @property
    def corder(self) -> int:
        ...

    @property
    def cset(self) -> H5T_cset_t:
        ...

    @property
    def u(self) -> hsize_t:
        ...

class _LinkVisitor:

    def __init__(self, func) -> None:
        ...

class LinkProxy:

    def __init__(self, id_: hid_t) -> None:
        ...

    def __richcmp__(self, other: object, how: int) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    @with_phil
    def create_hard(self, new_name: str, cur_loc: GroupID, cur_name: str, lcpl: PropID=None, lapl: PropID=None) -> None:
        ...

    @with_phil
    def create_soft(self, new_name: str, target: str, lcpl: PropID=None, lapl: PropID=None) -> None:
        ...

    @with_phil
    def create_external(self, link_name: str, file_name: str, obj_name: str, lcpl: PropID=None, lapl: PropID=None) -> None:
        ...

    @with_phil
    def get_val(self, name: str, lapl: PropID=None) -> bytes | tuple[bytes, bytes]:
        ...

    @with_phil
    def move(self, src_name: str, dst_loc: GroupID, dst_name: str, lcpl: PropID=None, lapl: PropID=None) -> None:
        ...

    @with_phil
    def exists(self, name: str, lapl: PropID=None) -> bool:
        ...

    @with_phil
    def get_info(self, name: str, index: int=-1, *, lapl: PropID=None) -> LinkInfo:
        ...

    @with_phil
    def visit(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0) -> object:
        ...

    @with_phil
    def iterate(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0, idx: hsize_t=0) -> tuple[object, hsize_t]:
        ...
TYPE_HARD: int = ...
TYPE_SOFT: int = ...
TYPE_EXTERNAL: int = ...
