# This file was generated by stubgen-pyx v0.2.10 from h5py\h5l.pyx

"""
API for the "H5L" family of link-related operations.  Defines the class
LinkProxy, which comes attached to GroupID objects as <obj>.links.
"""
from ._objects import with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class LinkInfo:

    @property
    def type(self):
        """ Integer type code for link (h5l.TYPE_*) """

    @property
    def corder_valid(self):
        """ Indicates if the creation order is valid """

    @property
    def corder(self):
        """ Creation order """

    @property
    def cset(self):
        """ Integer type code for character set (h5t.CSET_*) """

    @property
    def u(self):
        """ Either the address of a hard link or the size of a soft/UD link """

class _LinkVisitor:
    """ Helper class for iteration callback """

    def __init__(self, func):
        ...

class LinkProxy:
    """
    Proxy class which provides access to the HDF5 "H5L" API.

    These come attached to GroupID objects as "obj.links".  Since every
    H5L function operates on at least one group, the methods provided
    operate on their parent group identifier.  For example::

        >>> g = h5g.open(fid, '/')
        >>> g.links.exists("MyGroup")
        True
        >>> g.links.exists("FooBar")
        False

    * Hashable: No
    * Equality: Undefined

    You will note that this class does *not* inherit from ObjectID.
    """

    def __init__(self, id_: hid_t):
        ...

    def __richcmp__(self, other: object, how: int):
        ...

    def __hash__(self):
        ...

    @with_phil
    def create_hard(self, new_name: str, cur_loc: GroupID, cur_name: str, lcpl: PropID=None, lapl: PropID=None):
        """ (STRING new_name, GroupID cur_loc, STRING cur_name,
        PropID lcpl=None, PropID lapl=None)

        Create a new hard link in this group pointing to an existing link
        in another group.
        """

    @with_phil
    def create_soft(self, new_name: str, target: str, lcpl: PropID=None, lapl: PropID=None):
        """(STRING new_name, STRING target, PropID lcpl=None, PropID lapl=None)

        Create a new soft link in this group, with the given string value.
        The link target does not need to exist.
        """

    @with_phil
    def create_external(self, link_name: str, file_name: str, obj_name: str, lcpl: PropID=None, lapl: PropID=None):
        """(STRING link_name, STRING file_name, STRING obj_name,
        PropLCID lcpl=None, PropLAID lapl=None)

        Create a new external link, pointing to an object in another file.
        """

    @with_phil
    def get_val(self, name: str, lapl: PropID=None):
        """(STRING name, PropLAID lapl=None) => STRING or TUPLE(file, obj)

        Get the string value of a soft link, or a 2-tuple representing
        the contents of an external link.
        """

    @with_phil
    def move(self, src_name: str, dst_loc: GroupID, dst_name: str, lcpl: PropID=None, lapl: PropID=None):
        """ (STRING src_name, GroupID dst_loc, STRING dst_name)

        Move a link to a new location in the file.
        """

    @with_phil
    def exists(self, name: str, lapl: PropID=None):
        """ (STRING name, PropID lapl=None) => BOOL

        Check if a link of the specified name exists in this group.
        """

    @with_phil
    def get_info(self, name: str, index: int=-1, *, lapl: PropID=None):
        """(STRING name=, INT index=, **kwds) => LinkInfo instance

        Get information about a link, either by name or its index.

        Keywords:
        """

    @with_phil
    def visit(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0):
        """(CALLABLE func, **kwds) => <Return value from func>

        Iterate a function or callable object over all groups below this
        one.  Your callable should conform to the signature::

            func(STRING name) => Result

        or if the keyword argument "info" is True::

            func(STRING name, LinkInfo info) => Result

        Returning None or a logical False continues iteration; returning
        anything else aborts iteration and returns that value.

        BOOL info (False)
            Provide a LinkInfo instance to callback

        STRING obj_name (".")
            Visit this subgroup instead

        PropLAID lapl (None)
            Link access property list for "obj_name"

        INT idx_type (h5.INDEX_NAME)

        INT order (h5.ITER_INC)
        """

    @with_phil
    def iterate(self, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0, idx: hsize_t=0):
        """(CALLABLE func, **kwds) => <Return value from func>, <index to restart at>

        Iterate a function or callable object over all groups in this
        one.  Your callable should conform to the signature::

            func(STRING name) => Result

        or if the keyword argument "info" is True::

            func(STRING name, LinkInfo info) => Result

        Returning None or a logical False continues iteration; returning
        anything else aborts iteration and returns that value.

        BOOL info (False)
            Provide a LinkInfo instance to callback

        STRING obj_name (".")
            Visit this subgroup instead

        PropLAID lapl (None)
            Link access property list for "obj_name"

        INT idx_type (h5.INDEX_NAME)

        INT order (h5.ITER_INC)

        hsize_t idx (0)
            The index to start iterating at
        """
TYPE_HARD = ...
TYPE_SOFT = ...
TYPE_EXTERNAL = ...