# This file was generated by stubgen-pyx v0.2.10 from h5py\h5o.pyx

"""
Module for HDF5 "H5O" functions.
"""
import cython

from ._objects import ObjectID, with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class _ObjInfoBase:
    ...

class _OHdrMesg(_ObjInfoBase):

    @property
    def present(self):
        ...

    @property
    def shared(self):
        ...

    def _hash(self):
        ...

class _OHdrSpace(_ObjInfoBase):

    @property
    def total(self):
        ...

    @property
    def meta(self):
        ...

    @property
    def mesg(self):
        ...

    @property
    def free(self):
        ...

    def _hash(self):
        ...

class _OHdr(_ObjInfoBase):
    space: _OHdrSpace
    mesg: _OHdrMesg

    @property
    def version(self):
        ...

    @property
    def nmesgs(self):
        ...

    @property
    def nchunks(self):
        ...

    @property
    def flags(self):
        ...

    def __init__(self):
        ...

    def _hash(self):
        ...

class _ObjMetaInfo:

    @property
    def index_size(self):
        ...

    @property
    def heap_size(self):
        ...

    def _hash(self):
        ...

class _OMetaSize(_ObjInfoBase):
    obj: _ObjMetaInfo
    attr: _ObjMetaInfo

    def __init__(self):
        ...

    def _hash(self):
        ...

class _ObjInfo(_ObjInfoBase):

    @property
    def fileno(self):
        ...

    @property
    def addr(self):
        ...

    @property
    def type(self):
        ...

    @property
    def rc(self):
        ...

    @property
    def atime(self):
        ...

    @property
    def mtime(self):
        ...

    @property
    def ctime(self):
        ...

    @property
    def btime(self):
        ...

    @property
    def num_attrs(self):
        ...

    def _hash(self):
        ...

class ObjInfo(_ObjInfo):
    """
    Represents the H5O_info_t structure
    """
    hdr: _OHdr
    meta_size: _OMetaSize

    def __init__(self):
        ...

    def __copy__(self):
        ...

class _ObjectVisitor:

    def __init__(self, func):
        ...
TYPE_GROUP = ...
TYPE_DATASET = ...
TYPE_NAMED_DATATYPE = ...
COPY_SHALLOW_HIERARCHY_FLAG = ...
COPY_EXPAND_SOFT_LINK_FLAG = ...
COPY_EXPAND_EXT_LINK_FLAG = ...
COPY_EXPAND_REFERENCE_FLAG = ...
COPY_WITHOUT_ATTR_FLAG = ...
COPY_PRESERVE_NULL_FLAG = ...

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    """(ObjectID loc, STRING name=, INT index=, **kwds) => ObjInfo

    Get information describing an object in an HDF5 file.  Provide the object
    itself, or the containing group and exactly one of "name" or "index".

    STRING obj_name (".")
        When "index" is specified, look in this subgroup instead.
        Otherwise ignored.

    PropID lapl (None)
        Link access property list

    INT index_type (h5.INDEX_NAME)

    INT order (h5.ITER_INC)
    """

@with_phil
def exists_by_name(loc: ObjectID, name: str, lapl: PropID=None):
    """ (ObjectID loc, STRING name, PropID lapl=None) => BOOL exists

    Determines whether a link resolves to an actual object.
    """

@with_phil
def open(loc: ObjectID, name: str, lapl: PropID=None):
    """(ObjectID loc, STRING name, PropID lapl=None) => ObjectID

    Open a group, dataset, or named datatype attached to an existing group.
    """

@with_phil
def link(obj: ObjectID, loc: GroupID, name: str, lcpl: PropID=None, lapl: PropID=None):
    """(ObjectID obj, GroupID loc, STRING name, PropID lcpl=None,
    PropID lapl=None)

    Create a new hard link to an object.  Useful for objects created with
    h5g.create_anon() or h5d.create_anon().
    """

@with_phil
def copy(src_loc: ObjectID, src_name: str, dst_loc: GroupID, dst_name: str, copypl: PropID=None, lcpl: PropID=None):
    """(ObjectID src_loc, STRING src_name, GroupID dst_loc, STRING dst_name,
    PropID copypl=None, PropID lcpl=None)

    Copy a group, dataset or named datatype from one location to another.  The
    source and destination need not be in the same file.

    The default behavior is a recursive copy of the object and all objects
    below it.  This behavior is modified via the "copypl" property list.
    """

@with_phil
def set_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None):
    """(ObjectID loc, STRING comment, **kwds)

    Set the comment for any-file resident object.  Keywords:

    STRING obj_name (".")
        Set comment on this group member instead

    PropID lapl (None)
        Link access property list
    """

@with_phil
def get_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None):
    """(ObjectID loc, STRING comment, **kwds)

    Get the comment for any-file resident object.  Keywords:

    STRING obj_name (".")
        Set comment on this group member instead

    PropID lapl (None)
        Link access property list
    """

@with_phil
def visit(loc: ObjectID, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0):
    """(ObjectID loc, CALLABLE func, **kwds) => <Return value from func>

    Iterate a function or callable object over all objects below the
    specified one.  Your callable should conform to the signature::

        func(STRING name) => Result

    or if the keyword argument "info" is True::

        func(STRING name, ObjInfo info) => Result

    Returning None continues iteration; returning anything else aborts
    iteration and returns that value.  Keywords:

    BOOL info (False)
        Callback is func(STRING, Objinfo)

    STRING obj_name (".")
        Visit a subgroup of "loc" instead

    PropLAID lapl (None)
        Control how "obj_name" is interpreted

    INT idx_type (h5.INDEX_NAME)
        What indexing strategy to use

    INT order (h5.ITER_INC)
        Order in which iteration occurs

    Compatibility note:  No callback is executed for the starting path ("."),
    as some versions of HDF5 don't correctly handle a return value for this
    case.  This differs from the behavior of the native H5Ovisit, which
    provides a literal "." as the first value.
    """