# This file was generated by stubgen-pyx v0.2.11 from h5py\h5o.pyx

import cython

from ._objects import ObjectID, with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class _ObjInfoBase:
    ...

class _OHdrMesg(_ObjInfoBase):

    @property
    def present(self):
        ...

    @property
    def shared(self):
        ...

    def _hash(self):
        ...

class _OHdrSpace(_ObjInfoBase):

    @property
    def total(self):
        ...

    @property
    def meta(self):
        ...

    @property
    def mesg(self):
        ...

    @property
    def free(self):
        ...

    def _hash(self):
        ...

class _OHdr(_ObjInfoBase):
    space: _OHdrSpace
    mesg: _OHdrMesg

    @property
    def version(self):
        ...

    @property
    def nmesgs(self):
        ...

    @property
    def nchunks(self):
        ...

    @property
    def flags(self):
        ...

    def __init__(self):
        ...

    def _hash(self):
        ...

class _ObjMetaInfo:

    @property
    def index_size(self):
        ...

    @property
    def heap_size(self):
        ...

    def _hash(self):
        ...

class _OMetaSize(_ObjInfoBase):
    obj: _ObjMetaInfo
    attr: _ObjMetaInfo

    def __init__(self):
        ...

    def _hash(self):
        ...

class _ObjInfo(_ObjInfoBase):

    @property
    def fileno(self):
        ...

    @property
    def addr(self):
        ...

    @property
    def type(self):
        ...

    @property
    def rc(self):
        ...

    @property
    def atime(self):
        ...

    @property
    def mtime(self):
        ...

    @property
    def ctime(self):
        ...

    @property
    def btime(self):
        ...

    @property
    def num_attrs(self):
        ...

    def _hash(self):
        ...

class ObjInfo(_ObjInfo):
    hdr: _OHdr
    meta_size: _OMetaSize

    def __init__(self):
        ...

    def __copy__(self):
        ...

class _ObjectVisitor:

    def __init__(self, func):
        ...
TYPE_GROUP = ...
TYPE_DATASET = ...
TYPE_NAMED_DATATYPE = ...
COPY_SHALLOW_HIERARCHY_FLAG = ...
COPY_EXPAND_SOFT_LINK_FLAG = ...
COPY_EXPAND_EXT_LINK_FLAG = ...
COPY_EXPAND_REFERENCE_FLAG = ...
COPY_WITHOUT_ATTR_FLAG = ...
COPY_PRESERVE_NULL_FLAG = ...

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None):
    ...

@with_phil
def exists_by_name(loc: ObjectID, name: str, lapl: PropID=None):
    ...

@with_phil
def open(loc: ObjectID, name: str, lapl: PropID=None):
    ...

@with_phil
def link(obj: ObjectID, loc: GroupID, name: str, lcpl: PropID=None, lapl: PropID=None):
    ...

@with_phil
def copy(src_loc: ObjectID, src_name: str, dst_loc: GroupID, dst_name: str, copypl: PropID=None, lcpl: PropID=None):
    ...

@with_phil
def set_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@with_phil
def get_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None):
    ...

@with_phil
def visit(loc: ObjectID, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0):
    ...