# This file was generated by stubgen-pyx v0.2.12 from h5py\h5o.pyx

import cython

from ._objects import ObjectID, with_phil
from .defs import *
from .h5g import GroupID
from .h5p import PropID


class _ObjInfoBase:
    ...

class _OHdrMesg(_ObjInfoBase):

    @property
    def present(self) -> int:
        ...

    @property
    def shared(self) -> int:
        ...

    def _hash(self) -> int:
        ...

class _OHdrSpace(_ObjInfoBase):

    @property
    def total(self) -> int:
        ...

    @property
    def meta(self) -> int:
        ...

    @property
    def mesg(self) -> dict:
        ...

    @property
    def free(self) -> int:
        ...

    def _hash(self) -> int:
        ...

class _OHdr(_ObjInfoBase):
    space: _OHdrSpace
    mesg: _OHdrMesg

    @property
    def version(self) -> int:
        ...

    @property
    def nmesgs(self) -> int:
        ...

    @property
    def nchunks(self) -> int:
        ...

    @property
    def flags(self) -> int:
        ...

    def __init__(self) -> None:
        ...

    def _hash(self) -> int:
        ...

class _ObjMetaInfo:

    @property
    def index_size(self) -> int:
        ...

    @property
    def heap_size(self) -> hsize_t:
        ...

    def _hash(self) -> int:
        ...

class _OMetaSize(_ObjInfoBase):
    obj: _ObjMetaInfo
    attr: _ObjMetaInfo

    def __init__(self) -> None:
        ...

    def _hash(self) -> int:
        ...

class _ObjInfo(_ObjInfoBase):

    @property
    def fileno(self) -> int:
        ...

    @property
    def addr(self) -> haddr_t:
        ...

    @property
    def type(self) -> int:
        ...

    @property
    def rc(self) -> int:
        ...

    @property
    def atime(self) -> time_t:
        ...

    @property
    def mtime(self) -> time_t:
        ...

    @property
    def ctime(self) -> time_t:
        ...

    @property
    def btime(self) -> time_t:
        ...

    @property
    def num_attrs(self) -> hsize_t:
        ...

    def _hash(self) -> int:
        ...

class ObjInfo(_ObjInfo):
    hdr: _OHdr
    meta_size: _OMetaSize

    def __init__(self) -> None:
        ...

    def __copy__(self) -> ObjInfo:
        ...

class _ObjectVisitor:

    def __init__(self, func) -> None:
        ...
TYPE_GROUP: int = ...
TYPE_DATASET: int = ...
TYPE_NAMED_DATATYPE: int = ...
COPY_SHALLOW_HIERARCHY_FLAG: int = ...
COPY_EXPAND_SOFT_LINK_FLAG: int = ...
COPY_EXPAND_EXT_LINK_FLAG: int = ...
COPY_EXPAND_REFERENCE_FLAG: int = ...
COPY_WITHOUT_ATTR_FLAG: int = ...
COPY_PRESERVE_NULL_FLAG: int = ...

@cython.binding(False)
@with_phil
def get_info(loc: ObjectID, name: str=..., index: int=-1, *, obj_name: str='.', index_type: int=..., order: int=..., lapl: PropID=None) -> ObjInfo:
    ...

@with_phil
def exists_by_name(loc: ObjectID, name: str, lapl: PropID=None) -> bool:
    ...

@with_phil
def open(loc: ObjectID, name: str, lapl: PropID=None) -> ObjectID:
    ...

@with_phil
def link(obj: ObjectID, loc: GroupID, name: str, lcpl: PropID=None, lapl: PropID=None) -> None:
    ...

@with_phil
def copy(src_loc: ObjectID, src_name: str, dst_loc: GroupID, dst_name: str, copypl: PropID=None, lcpl: PropID=None) -> None:
    ...

@with_phil
def set_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None) -> None:
    ...

@with_phil
def get_comment(loc: ObjectID, comment: str, *, obj_name: str='.', lapl: PropID=None) -> bytes:
    ...

@with_phil
def visit(loc: ObjectID, func: object, *, idx_type: int=..., order: int=..., obj_name: str='.', lapl: PropID=None, info: bool=0) -> object:
    ...
