# This file was generated by stubgen-pyx v0.2.12 from h5py\h5p.pyx

from numpy import ndarray

from ._objects import ObjectID, with_phil
from .defs import *
from .h5ac import CacheConfig
from .h5s import SpaceID


class PropID(ObjectID):

    @with_phil
    def equal(self, plist: PropID) -> bool:
        ...

    def __richcmp__(self, other: object, how: int) -> bool:
        ...

    def __hash__(self) -> int:
        ...

class PropClassID(PropID):

    def __richcmp__(self, other: object, how: int) -> bool:
        ...

    def __hash__(self) -> int:
        ...

class PropInstanceID(PropID):

    @with_phil
    def copy(self) -> PropID:
        ...

    def get_class(self) -> PropClassID:
        ...

class PropCreateID(PropInstanceID):
    ...

class PropCopyID(PropInstanceID):

    @with_phil
    def set_copy_object(self, flags: int) -> None:
        ...

    @with_phil
    def get_copy_object(self) -> int:
        ...

class PropFCID(PropOCID):

    @with_phil
    def get_version(self) -> tuple[int, int, int, int]:
        ...

    @with_phil
    def set_userblock(self, size: hsize_t) -> None:
        ...

    @with_phil
    def get_userblock(self) -> hsize_t:
        ...

    @with_phil
    def set_sizes(self, addr: int, size: int) -> None:
        ...

    @with_phil
    def get_sizes(self) -> tuple[int, int]:
        ...

    @with_phil
    def set_link_creation_order(self, flags: int) -> None:
        ...

    @with_phil
    def get_link_creation_order(self) -> int:
        ...

    @with_phil
    def set_file_space_strategy(self, strategy: int, persist: bool, threshold: int) -> None:
        ...

    @with_phil
    def get_file_space_strategy(self) -> tuple[H5F_fspace_strategy_t, hbool_t, hsize_t]:
        ...

    @with_phil
    def set_file_space_page_size(self, fsp_size: hsize_t) -> None:
        ...

    @with_phil
    def get_file_space_page_size(self) -> hsize_t:
        ...

class PropDCID(PropOCID):

    @with_phil
    def set_layout(self, layout_code: int) -> None:
        ...

    @with_phil
    def get_layout(self) -> int:
        ...

    @with_phil
    def set_chunk(self, chunksize: object) -> None:
        ...

    @with_phil
    def get_chunk(self) -> tuple:
        ...

    @with_phil
    def set_fill_value(self, value: ndarray) -> None:
        ...

    @with_phil
    def get_fill_value(self, value: ndarray) -> None:
        ...

    @with_phil
    def fill_value_defined(self) -> int:
        ...

    @with_phil
    def set_fill_time(self, fill_time: int) -> None:
        ...

    @with_phil
    def get_fill_time(self) -> int:
        ...

    @with_phil
    def set_alloc_time(self, alloc_time: int) -> None:
        ...

    @with_phil
    def get_alloc_time(self) -> int:
        ...

    @with_phil
    def set_filter(self, filter_code: int, flags: int=0, values: object=None) -> None:
        ...

    @with_phil
    def all_filters_avail(self) -> bool:
        ...

    @with_phil
    def get_nfilters(self) -> int:
        ...

    @with_phil
    def get_filter(self, filter_idx: int) -> tuple[int, int, tuple[int, ...], str]:
        ...

    @with_phil
    def _has_filter(self, filter_code: int) -> bool:
        ...

    @with_phil
    def get_filter_by_id(self, filter_code: int) -> tuple[int, tuple[int, ...], str]:
        ...

    @with_phil
    def remove_filter(self, filter_class: int) -> None:
        ...

    @with_phil
    def set_deflate(self, level: int=5) -> None:
        ...

    @with_phil
    def set_fletcher32(self) -> None:
        ...

    @with_phil
    def set_shuffle(self) -> None:
        ...

    @with_phil
    def set_szip(self, options: int, pixels_per_block: int) -> None:
        ...

    @with_phil
    def set_scaleoffset(self, scale_type: H5Z_SO_scale_type_t, scale_factor: int) -> None:
        ...

    @with_phil
    def set_external(self, name, offset, size) -> None:
        ...

    @with_phil
    def get_external_count(self) -> int:
        ...

    @with_phil
    def get_external(self, idx=0) -> tuple[str, off_t, hsize_t]:
        ...

    @with_phil
    def set_virtual(self, vspace: SpaceID, src_file_name: str, src_dset_name: str, src_space: SpaceID) -> None:
        ...

    @with_phil
    def get_virtual_count(self) -> int:
        ...

    @with_phil
    def get_virtual_dsetname(self, index: int=0) -> str:
        ...

    @with_phil
    def get_virtual_filename(self, index: int=0) -> str:
        ...

    @with_phil
    def get_virtual_vspace(self, index: int=0) -> SpaceID:
        ...

    @with_phil
    def get_virtual_srcspace(self, index: int=0) -> SpaceID:
        ...

class PropFAID(PropInstanceID):

    @with_phil
    def set_fclose_degree(self, close_degree: int) -> None:
        ...

    @with_phil
    def get_fclose_degree(self) -> int:
        ...

    @with_phil
    def set_fapl_core(self, block_size: int=..., backing_store: hbool_t=1) -> None:
        ...

    @with_phil
    def get_fapl_core(self) -> tuple[int, bool]:
        ...

    @with_phil
    def set_fapl_family(self, memb_size: hsize_t=2147483647, memb_fapl: PropID=None) -> None:
        ...

    @with_phil
    def get_fapl_family(self) -> tuple[hsize_t, PropFAID]:
        ...

    @with_phil
    def set_fapl_log(self, logfile: str, flags: int, buf_size: int) -> None:
        ...

    @with_phil
    def set_fapl_sec2(self) -> None:
        ...

    @with_phil
    def set_fapl_stdio(self) -> None:
        ...

    @with_phil
    def set_fapl_split(self, meta_ext='-m.h5', meta_plist_id: PropID=None, raw_ext='-r.h5', raw_plist_id: PropID=None) -> None:
        ...

    @with_phil
    def set_driver(self, driver_id: hid_t) -> None:
        ...

    @with_phil
    def set_fileobj_driver(self, driver_id: hid_t, fileobj: object) -> None:
        ...

    @with_phil
    def get_driver(self) -> int:
        ...

    @with_phil
    def set_cache(self, mdc: int, rdcc: int, rdcc_nbytes: int, rdcc_w0: float) -> None:
        ...

    @with_phil
    def get_cache(self) -> tuple[int, int, int, float]:
        ...

    @with_phil
    def set_sieve_buf_size(self, size: int) -> None:
        ...

    @with_phil
    def get_sieve_buf_size(self) -> int:
        ...

    @with_phil
    def set_libver_bounds(self, low: int, high: int) -> None:
        ...

    @with_phil
    def set_meta_block_size(self, size: int) -> None:
        ...

    @with_phil
    def get_meta_block_size(self) -> int:
        ...

    @with_phil
    def get_libver_bounds(self) -> tuple[int, int]:
        ...

    @with_phil
    def get_mdc_config(self) -> CacheConfig:
        ...

    @with_phil
    def set_mdc_config(self, config: CacheConfig) -> None:
        ...

    @with_phil
    def get_alignment(self) -> tuple[hsize_t, hsize_t]:
        ...

    @with_phil
    def set_alignment(self, threshold, alignment) -> None:
        ...

    @with_phil
    def set_file_image(self, image) -> None:
        ...

    @with_phil
    def set_page_buffer_size(self, buf_size: int, min_meta_per: int=0, min_raw_per: int=0) -> None:
        ...

    @with_phil
    def get_page_buffer_size(self) -> tuple[int, int, int]:
        ...

    @with_phil
    def get_file_locking(self) -> tuple[hbool_t, hbool_t]:
        ...

    @with_phil
    def set_file_locking(self, use_file_locking: bool, ignore_when_disabled: bool) -> None:
        ...

class PropLCID(PropCreateID):

    @with_phil
    def set_char_encoding(self, encoding: int) -> None:
        ...

    @with_phil
    def get_char_encoding(self) -> int:
        ...

    @with_phil
    def set_create_intermediate_group(self, create: bool) -> None:
        ...

    @with_phil
    def get_create_intermediate_group(self) -> bool:
        ...

class PropLAID(PropInstanceID):

    def __cinit__(self, *args) -> None:
        ...

    def __dealloc__(self) -> None:
        ...

    @with_phil
    def set_nlinks(self, nlinks: int) -> None:
        ...

    @with_phil
    def get_nlinks(self) -> int:
        ...

    @with_phil
    def set_elink_prefix(self, prefix: str) -> None:
        ...

    @with_phil
    def get_elink_prefix(self) -> bytes:
        ...

    @with_phil
    def set_elink_fapl(self, fapl: PropID) -> None:
        ...

    @with_phil
    def get_elink_fapl(self) -> PropFAID:
        ...

    @with_phil
    def set_elink_acc_flags(self, flags: int) -> None:
        ...

    @with_phil
    def get_elink_acc_flags(self) -> int:
        ...

class PropTCID(PropOCID):
    ...

class PropGCID(PropOCID):

    @with_phil
    def set_link_creation_order(self, flags: int) -> None:
        ...

    @with_phil
    def get_link_creation_order(self) -> int:
        ...

class PropOCID(PropCreateID):

    @with_phil
    def set_attr_creation_order(self, flags: int) -> None:
        ...

    @with_phil
    def get_attr_creation_order(self) -> int:
        ...

    @with_phil
    def set_attr_phase_change(self, max_compact=8, min_dense=6) -> None:
        ...

    @with_phil
    def get_attr_phase_change(self) -> tuple[int, int]:
        ...

    @with_phil
    def set_obj_track_times(self, track_times) -> None:
        ...

    @with_phil
    def get_obj_track_times(self) -> hbool_t:
        ...

class PropDAID(PropInstanceID):

    def __cinit__(self, *args) -> None:
        ...

    def __dealloc__(self) -> None:
        ...

    @with_phil
    def set_chunk_cache(self, rdcc_nslots: int, rdcc_nbytes: int, rdcc_w0: float) -> None:
        ...

    @with_phil
    def get_chunk_cache(self) -> tuple[int, int, float]:
        ...

    @with_phil
    def get_efile_prefix(self) -> bytes:
        ...

    @with_phil
    def set_efile_prefix(self, prefix: str) -> None:
        ...

    @with_phil
    def set_virtual_view(self, view: int) -> None:
        ...

    @with_phil
    def get_virtual_view(self) -> int:
        ...

    @with_phil
    def set_virtual_printf_gap(self, gap_size: hsize_t=0) -> None:
        ...

    @with_phil
    def get_virtual_printf_gap(self) -> hsize_t:
        ...

    @with_phil
    def get_virtual_prefix(self) -> bytes:
        ...

    @with_phil
    def set_virtual_prefix(self, prefix: str) -> None:
        ...

class PropDXID(PropInstanceID):
    ...
NO_CLASS: PropClassID = ...
FILE_CREATE: PropClassID = ...
FILE_ACCESS: PropClassID = ...
DATASET_CREATE: PropClassID = ...
DATASET_XFER: PropClassID = ...
DATASET_ACCESS: PropClassID = ...
OBJECT_COPY: PropClassID = ...
LINK_CREATE: PropClassID = ...
LINK_ACCESS: PropClassID = ...
GROUP_CREATE: PropClassID = ...
OBJECT_CREATE: PropClassID = ...
CRT_ORDER_TRACKED: int = ...
CRT_ORDER_INDEXED: int = ...
DEFAULT = None

@with_phil
def create(cls: PropClassID) -> PropID:
    ...
