# This file was generated by stubgen-pyx v0.2.11 from h5py\h5p.pyx

from numpy import ndarray

from ._objects import ObjectID, with_phil
from .defs import *
from .h5ac import CacheConfig
from .h5s import SpaceID


class PropID(ObjectID):

    @with_phil
    def equal(self, plist: PropID):
        ...

    def __richcmp__(self, other: object, how: int):
        ...

    def __hash__(self):
        ...

class PropClassID(PropID):

    def __richcmp__(self, other: object, how: int):
        ...

    def __hash__(self):
        ...

class PropInstanceID(PropID):

    @with_phil
    def copy(self):
        ...

    def get_class(self):
        ...

class PropCreateID(PropInstanceID):
    ...

class PropCopyID(PropInstanceID):

    @with_phil
    def set_copy_object(self, flags: int):
        ...

    @with_phil
    def get_copy_object(self):
        ...

class PropFCID(PropOCID):

    @with_phil
    def get_version(self):
        ...

    @with_phil
    def set_userblock(self, size: hsize_t):
        ...

    @with_phil
    def get_userblock(self):
        ...

    @with_phil
    def set_sizes(self, addr: int, size: int):
        ...

    @with_phil
    def get_sizes(self):
        ...

    @with_phil
    def set_link_creation_order(self, flags: int):
        ...

    @with_phil
    def get_link_creation_order(self):
        ...

    @with_phil
    def set_file_space_strategy(self, strategy: int, persist: bool, threshold: int):
        ...

    @with_phil
    def get_file_space_strategy(self):
        ...

    @with_phil
    def set_file_space_page_size(self, fsp_size: hsize_t):
        ...

    @with_phil
    def get_file_space_page_size(self):
        ...

class PropDCID(PropOCID):

    @with_phil
    def set_layout(self, layout_code: int):
        ...

    @with_phil
    def get_layout(self):
        ...

    @with_phil
    def set_chunk(self, chunksize: object):
        ...

    @with_phil
    def get_chunk(self):
        ...

    @with_phil
    def set_fill_value(self, value: ndarray):
        ...

    @with_phil
    def get_fill_value(self, value: ndarray):
        ...

    @with_phil
    def fill_value_defined(self):
        ...

    @with_phil
    def set_fill_time(self, fill_time: int):
        ...

    @with_phil
    def get_fill_time(self):
        ...

    @with_phil
    def set_alloc_time(self, alloc_time: int):
        ...

    @with_phil
    def get_alloc_time(self):
        ...

    @with_phil
    def set_filter(self, filter_code: int, flags: int=0, values: object=None):
        ...

    @with_phil
    def all_filters_avail(self):
        ...

    @with_phil
    def get_nfilters(self):
        ...

    @with_phil
    def get_filter(self, filter_idx: int):
        ...

    @with_phil
    def _has_filter(self, filter_code: int):
        ...

    @with_phil
    def get_filter_by_id(self, filter_code: int):
        ...

    @with_phil
    def remove_filter(self, filter_class: int):
        ...

    @with_phil
    def set_deflate(self, level: int=5):
        ...

    @with_phil
    def set_fletcher32(self):
        ...

    @with_phil
    def set_shuffle(self):
        ...

    @with_phil
    def set_szip(self, options: int, pixels_per_block: int):
        ...

    @with_phil
    def set_scaleoffset(self, scale_type: H5Z_SO_scale_type_t, scale_factor: int):
        ...

    @with_phil
    def set_external(self, name, offset, size):
        ...

    @with_phil
    def get_external_count(self):
        ...

    @with_phil
    def get_external(self, idx=0):
        ...

    @with_phil
    def set_virtual(self, vspace: SpaceID, src_file_name: str, src_dset_name: str, src_space: SpaceID):
        ...

    @with_phil
    def get_virtual_count(self):
        ...

    @with_phil
    def get_virtual_dsetname(self, index: int=0):
        ...

    @with_phil
    def get_virtual_filename(self, index: int=0):
        ...

    @with_phil
    def get_virtual_vspace(self, index: int=0):
        ...

    @with_phil
    def get_virtual_srcspace(self, index: int=0):
        ...

class PropFAID(PropInstanceID):

    @with_phil
    def set_fclose_degree(self, close_degree: int):
        ...

    @with_phil
    def get_fclose_degree(self):
        ...

    @with_phil
    def set_fapl_core(self, block_size: int=..., backing_store: hbool_t=1):
        ...

    @with_phil
    def get_fapl_core(self):
        ...

    @with_phil
    def set_fapl_family(self, memb_size: hsize_t=2147483647, memb_fapl: PropID=None):
        ...

    @with_phil
    def get_fapl_family(self):
        ...

    @with_phil
    def set_fapl_log(self, logfile: str, flags: int, buf_size: int):
        ...

    @with_phil
    def set_fapl_sec2(self):
        ...

    @with_phil
    def set_fapl_stdio(self):
        ...

    @with_phil
    def set_fapl_split(self, meta_ext='-m.h5', meta_plist_id: PropID=None, raw_ext='-r.h5', raw_plist_id: PropID=None):
        ...

    @with_phil
    def set_driver(self, driver_id: hid_t):
        ...

    @with_phil
    def set_fileobj_driver(self, driver_id: hid_t, fileobj: object):
        ...

    @with_phil
    def get_driver(self):
        ...

    @with_phil
    def set_cache(self, mdc: int, rdcc: int, rdcc_nbytes: int, rdcc_w0: float):
        ...

    @with_phil
    def get_cache(self):
        ...

    @with_phil
    def set_sieve_buf_size(self, size: int):
        ...

    @with_phil
    def get_sieve_buf_size(self):
        ...

    @with_phil
    def set_libver_bounds(self, low: int, high: int):
        ...

    @with_phil
    def set_meta_block_size(self, size: int):
        ...

    @with_phil
    def get_meta_block_size(self):
        ...

    @with_phil
    def get_libver_bounds(self):
        ...

    @with_phil
    def get_mdc_config(self):
        ...

    @with_phil
    def set_mdc_config(self, config: CacheConfig):
        ...

    @with_phil
    def get_alignment(self):
        ...

    @with_phil
    def set_alignment(self, threshold, alignment):
        ...

    @with_phil
    def set_file_image(self, image):
        ...

    @with_phil
    def set_page_buffer_size(self, buf_size: int, min_meta_per: int=0, min_raw_per: int=0):
        ...

    @with_phil
    def get_page_buffer_size(self):
        ...

    @with_phil
    def get_file_locking(self):
        ...

    @with_phil
    def set_file_locking(self, use_file_locking: bool, ignore_when_disabled: bool):
        ...

class PropLCID(PropCreateID):

    @with_phil
    def set_char_encoding(self, encoding: int):
        ...

    @with_phil
    def get_char_encoding(self):
        ...

    @with_phil
    def set_create_intermediate_group(self, create: bool):
        ...

    @with_phil
    def get_create_intermediate_group(self):
        ...

class PropLAID(PropInstanceID):

    def __cinit__(self, *args):
        ...

    def __dealloc__(self):
        ...

    @with_phil
    def set_nlinks(self, nlinks: int):
        ...

    @with_phil
    def get_nlinks(self):
        ...

    @with_phil
    def set_elink_prefix(self, prefix: str):
        ...

    @with_phil
    def get_elink_prefix(self):
        ...

    @with_phil
    def set_elink_fapl(self, fapl: PropID):
        ...

    @with_phil
    def get_elink_fapl(self):
        ...

    @with_phil
    def set_elink_acc_flags(self, flags: int):
        ...

    @with_phil
    def get_elink_acc_flags(self):
        ...

class PropTCID(PropOCID):
    ...

class PropGCID(PropOCID):

    @with_phil
    def set_link_creation_order(self, flags: int):
        ...

    @with_phil
    def get_link_creation_order(self):
        ...

class PropOCID(PropCreateID):

    @with_phil
    def set_attr_creation_order(self, flags: int):
        ...

    @with_phil
    def get_attr_creation_order(self):
        ...

    @with_phil
    def set_attr_phase_change(self, max_compact=8, min_dense=6):
        ...

    @with_phil
    def get_attr_phase_change(self):
        ...

    @with_phil
    def set_obj_track_times(self, track_times):
        ...

    @with_phil
    def get_obj_track_times(self):
        ...

class PropDAID(PropInstanceID):

    def __cinit__(self, *args):
        ...

    def __dealloc__(self):
        ...

    @with_phil
    def set_chunk_cache(self, rdcc_nslots: int, rdcc_nbytes: int, rdcc_w0: float):
        ...

    @with_phil
    def get_chunk_cache(self):
        ...

    @with_phil
    def get_efile_prefix(self):
        ...

    @with_phil
    def set_efile_prefix(self, prefix: str):
        ...

    @with_phil
    def set_virtual_view(self, view: int):
        ...

    @with_phil
    def get_virtual_view(self):
        ...

    @with_phil
    def set_virtual_printf_gap(self, gap_size: hsize_t=0):
        ...

    @with_phil
    def get_virtual_printf_gap(self):
        ...

    @with_phil
    def get_virtual_prefix(self):
        ...

    @with_phil
    def set_virtual_prefix(self, prefix: str):
        ...

class PropDXID(PropInstanceID):
    ...
NO_CLASS = ...
FILE_CREATE = ...
FILE_ACCESS = ...
DATASET_CREATE = ...
DATASET_XFER = ...
DATASET_ACCESS = ...
OBJECT_COPY = ...
LINK_CREATE = ...
LINK_ACCESS = ...
GROUP_CREATE = ...
OBJECT_CREATE = ...
CRT_ORDER_TRACKED = ...
CRT_ORDER_INDEXED = ...
DEFAULT = None

@with_phil
def create(cls: PropClassID):
    ...