# This file was generated by stubgen-pyx v0.2.10 from h5py\h5pl.pyx

"""
Provides access to the low-level HDF5 "H5PL" plugins interface.

These functions are probably not thread safe.
"""
from .defs import *


def append(search_path):
    """(STRING search_path)

    Add a directory to the end of the plugin search path.
    """

def prepend(search_path):
    """(STRING search_path)

    Add a directory to the start of the plugin search path.
    """

def replace(search_path, index: int):
    """(STRING search_path, UINT index)

    Replace the directory at the given index in the plugin search path.
    """

def insert(search_path, index: int):
    """(STRING search_path, UINT index)

    Insert a directory at the given index in the plugin search path.
    """

def remove(index: int):
    """(UINT index)

    Remove the specified entry from the plugin search path.
    """

def get(index: int):
    """(UINT index) => STRING

    Get the directory path at the given index (starting from 0) in the
    plugin search path. Returns a Python bytes object.
    """

def size():
    """() => UINT

    Get the number of directories currently in the plugin search path.
    """