# This file was generated by stubgen-pyx v0.2.11 from h5py\h5pl.pyx

from .defs import *


def append(search_path):
    ...

def prepend(search_path):
    ...

def replace(search_path, index: int):
    ...

def insert(search_path, index: int):
    ...

def remove(index: int):
    ...

def get(index: int):
    ...

def size():
    ...