# This file was generated by stubgen-pyx v0.2.12 from h5py\h5pl.pyx

from .defs import *


def append(search_path) -> None:
    ...

def prepend(search_path) -> None:
    ...

def replace(search_path, index: int) -> None:
    ...

def insert(search_path, index: int) -> None:
    ...

def remove(index: int) -> None:
    ...

def get(index: int) -> object:
    ...

def size() -> int:
    ...
