# This file was generated by stubgen-pyx v0.2.10 from h5py\h5r.pyx

"""
H5R API for object and region references.
"""
from typing import TypeAlias as _TypeAlias

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID


class Reference:
    """
    Opaque representation of an HDF5 reference.

    Objects of this class are created exclusively by the library and
    cannot be modified.  The read-only attribute "typecode" determines
    whether the reference is to an object in an HDF5 file (OBJECT)
    or a dataset region (DATASET_REGION).

    The object's truth value indicates whether it contains a nonzero
    reference.  This does not guarantee that is valid, but is useful
    for rejecting "background" elements in a dataset.

    Defined attributes:
      cdef ref_u ref
      cdef readonly int typecode
      cdef readonly size_t typesize
    """

    def __cinit__(self, *args, **kwds):
        ...

    def __bool__(self):
        ...

    def __repr__(self):
        ...

class RegionReference(Reference):
    """
    Opaque representation of an HDF5 region reference.

    This is a subclass of Reference which exists mainly for programming
    convenience.
    """

    def __cinit__(self, *args, **kwds):
        ...

    def __repr__(self):
        ...
OBJECT = ...
DATASET_REGION = ...
hobj_ref_t: _TypeAlias = ...

@with_phil
def create(loc: ObjectID, name: str, ref_type: int, space: ObjectID=None):
    """(ObjectID loc, STRING name, INT ref_type, SpaceID space=None)
    => ReferenceObject ref

    Create a new reference. The value of ref_type determines the kind
    of reference created:

    OBJECT
        Reference to an object in an HDF5 file.  Parameters "loc"
        and "name" identify the object; "space" is unused.

    DATASET_REGION
        Reference to a dataset region.  Parameters "loc" and
        "name" identify the dataset; the selection on "space"
        identifies the region.
    """

@with_phil
def dereference(ref: Reference, id: ObjectID, oapl: PropID=None):
    """(Reference ref, ObjectID id) => ObjectID or None

    Open the object pointed to by the reference and return its
    identifier.  The file identifier (or the identifier for any object
    in the file) must also be provided.  Returns None if the reference
    is zero-filled.

    The reference may be either Reference or RegionReference.
    """

@with_phil
def get_region(ref: RegionReference, id: ObjectID):
    """(Reference ref, ObjectID id) => SpaceID or None

    Retrieve the dataspace selection pointed to by the reference.
    Returns a copy of the dataset's dataspace, with the appropriate
    elements selected.  The file identifier or the identifier of any
    object in the file (including the dataset itself) must also be
    provided.

    The reference object must be a RegionReference.  If it is zero-filled,
    returns None.
    """

@with_phil
def get_obj_type(ref: Reference, id: ObjectID):
    """(Reference ref, ObjectID id) => INT obj_code or None

    Determine what type of object the reference points to.  The
    reference may be a Reference or RegionReference.  The file
    identifier or the identifier of any object in the file must also
    be provided.

    The return value is one of:

    - h5o.TYPE_GROUP
    - h5o.TYPE_DATASET
    - h5o.TYPE_NAMED_DATATYPE

    If the reference is zero-filled, returns None.
    """

@with_phil
def get_name(ref: Reference, loc: ObjectID):
    """(Reference ref, ObjectID loc) => STRING name

    Determine the name of the object pointed to by this reference.
    """