# This file was generated by stubgen-pyx v0.2.11 from h5py\h5r.pyx

from typing import TypeAlias as _TypeAlias

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID


class Reference:

    def __cinit__(self, *args, **kwds):
        ...

    def __bool__(self):
        ...

    def __repr__(self):
        ...

class RegionReference(Reference):

    def __cinit__(self, *args, **kwds):
        ...

    def __repr__(self):
        ...
OBJECT = ...
DATASET_REGION = ...
hobj_ref_t: _TypeAlias = ...

@with_phil
def create(loc: ObjectID, name: str, ref_type: int, space: ObjectID=None):
    ...

@with_phil
def dereference(ref: Reference, id: ObjectID, oapl: PropID=None):
    ...

@with_phil
def get_region(ref: RegionReference, id: ObjectID):
    ...

@with_phil
def get_obj_type(ref: Reference, id: ObjectID):
    ...

@with_phil
def get_name(ref: Reference, loc: ObjectID):
    ...