# This file was generated by stubgen-pyx v0.2.12 from h5py\h5r.pyx

from typing import TypeAlias as _TypeAlias

from ._objects import ObjectID, with_phil
from .defs import *
from .h5p import PropID
from .h5s import SpaceID


class Reference:

    def __cinit__(self, *args, **kwds) -> None:
        ...

    def __bool__(self) -> bool:
        ...

    def __repr__(self) -> str:
        ...

class RegionReference(Reference):

    def __cinit__(self, *args, **kwds) -> None:
        ...

    def __repr__(self) -> str:
        ...
OBJECT: int = ...
DATASET_REGION: int = ...
hobj_ref_t: _TypeAlias = haddr_t

@with_phil
def create(loc: ObjectID, name: str, ref_type: int, space: ObjectID=None) -> Reference:
    ...

@with_phil
def dereference(ref: Reference, id: ObjectID, oapl: PropID=None) -> ObjectID:
    ...

@with_phil
def get_region(ref: RegionReference, id: ObjectID) -> SpaceID:
    ...

@with_phil
def get_obj_type(ref: Reference, id: ObjectID) -> int | None:
    ...

@with_phil
def get_name(ref: Reference, loc: ObjectID) -> bytes | None:
    ...
