# This file was generated by stubgen-pyx v0.2.10 from h5py\h5s.pyx

"""
Low-level interface to the "H5S" family of data-space functions.
"""
from ._objects import ObjectID, with_phil
from .defs import *


class SpaceID(ObjectID):
    """
    Represents a dataspace identifier.

    Properties:

    shape
        Numpy-style shape tuple with dimensions.

    * Hashable: No
    * Equality: Unimplemented
    """

    @property
    def shape(self):
        """ Numpy-style shape tuple representing dimensions.  () == scalar.
        """

    @with_phil
    def copy(self):
        """() => SpaceID

        Create a new copy of this dataspace.
        """

    @with_phil
    def encode(self):
        """() => STRING

        Serialize a dataspace, including its selection.  Bear in mind you
        can also use the native Python pickling machinery to do this.
        """

    def __reduce__(self):
        ...

    def __setstate__(self, state):
        ...

    @with_phil
    def is_simple(self):
        """() => BOOL is_simple

        Determine if an existing dataspace is "simple" (including scalar
        dataspaces). Currently all HDF5 dataspaces are simple.
        """

    @with_phil
    def offset_simple(self, offset: object=None):
        """(TUPLE offset=None)

        Set the offset of a dataspace.  The length of the given tuple must
        match the rank of the dataspace. If None is provided (default),
        the offsets on all axes will be set to 0.
        """

    @with_phil
    def get_simple_extent_ndims(self):
        """() => INT rank

        Determine the rank of a "simple" (slab) dataspace.
        """

    @with_phil
    def get_simple_extent_dims(self, maxdims: int=0):
        """(BOOL maxdims=False) => TUPLE shape

        Determine the shape of a "simple" (slab) dataspace.  If "maxdims"
        is True, retrieve the maximum dataspace size instead.
        """

    @with_phil
    def get_simple_extent_npoints(self):
        """() => LONG npoints

        Determine the total number of elements in a dataspace.
        """

    @with_phil
    def get_simple_extent_type(self):
        """() => INT class_code

        Class code is either SCALAR or SIMPLE.
        """

    @with_phil
    def extent_copy(self, source: SpaceID):
        """(SpaceID source)

        Replace this dataspace's extent with another's, changing its
        typecode if necessary.
        """

    @with_phil
    def set_extent_simple(self, dims_tpl: object, max_dims_tpl: object=None):
        """(TUPLE dims_tpl, TUPLE max_dims_tpl=None)

        Reset the dataspace extent via a tuple of dimensions.
        Every element of dims_tpl must be a positive integer.

        You can optionally specify the maximum dataspace size. The
        special value UNLIMITED, as an element of max_dims, indicates
        an unlimited dimension.
        """

    @with_phil
    def set_extent_none(self):
        """()

        Remove the dataspace extent; typecode changes to NO_CLASS.
        """

    @with_phil
    def get_select_type(self):
        """ () => INT select_code

        Determine selection type.  Return values are:

        - SEL_NONE
        - SEL_ALL
        - SEL_POINTS
        - SEL_HYPERSLABS
        """

    @with_phil
    def get_select_npoints(self):
        """() => LONG npoints

        Determine the total number of points currently selected.
        Works for all selection techniques.
        """

    @with_phil
    def get_select_bounds(self):
        """() => (TUPLE start, TUPLE end)

        Determine the bounding box which exactly contains
        the current selection.
        """

    @with_phil
    def select_shape_same(self, space2: SpaceID):
        """(SpaceID space2) => BOOL

        Check if two selections are the same shape. HDF5 may read data
        faster if the source & destination selections are the same shape.
        """

    @with_phil
    def select_all(self):
        """()

        Select all points in the dataspace.
        """

    @with_phil
    def select_copy(self, src_id: SpaceID):
        """(SpaceID src_id)

        Copies the selection from another dataspace to this one (self).
        """

    @with_phil
    def select_none(self):
        """()

        Deselect entire dataspace.
        """

    @with_phil
    def select_valid(self):
        """() => BOOL

        Determine if the current selection falls within
        the dataspace extent.
        """

    @with_phil
    def get_select_elem_npoints(self):
        """() => LONG npoints

        Determine the number of elements selected in point-selection mode.
        """

    @with_phil
    def get_select_elem_pointlist(self):
        """() => NDARRAY

        Get a list of all selected elements.  Return is a Numpy array of
        unsigned ints, with shape ``(<npoints>, <space rank)``.
        """

    @with_phil
    def select_elements(self, coords: object, op: int=...):
        """(SEQUENCE coords, INT op=SELECT_SET)

        Select elements by specifying coordinates points.  The argument
        "coords" may be an ndarray or any nested sequence which can be
        converted to an array of uints with the shape::

            (<npoints>, <space rank>)

        Examples::

            >>> obj.shape
            (10, 10)
            >>> obj.select_elements([(1,2), (3,4), (5,9)])

        A zero-length selection (i.e. shape ``(0, <rank>)``) is not allowed
        by the HDF5 library.
        """

    @with_phil
    def get_select_hyper_nblocks(self):
        """() => LONG nblocks

        Get the number of hyperslab blocks currently selected.
        """

    @with_phil
    def get_select_hyper_blocklist(self):
        """() => NDARRAY

        Get the current hyperslab selection.  The returned array has shape::

            (<npoints>, 2, <rank>)

        and can be interpreted as a nested sequence::

            [ (corner_coordinate_1, opposite_coordinate_1), ... ]

        with length equal to the total number of blocks.
        """

    @with_phil
    def select_hyperslab(self, start: object, count: object, stride: object=None, block: object=None, op: int=...):
        """(TUPLE start, TUPLE count, TUPLE stride=None, TUPLE block=None,
             INT op=SELECT_SET)

        Select a block region from an existing dataspace.  See the HDF5
        documentation for the meaning of the "block" and "op" keywords.
        """

    @with_phil
    def combine_select(self, space2: SpaceID, op: int=...):
        """(SpaceID space2, INT op=SELECT_OR) => SpaceID

        Combine two hyperslab selections with an operation, returning a new
        dataspace with the resulting selection. The default operation is a union,
        so the resulting selection includes everything selected in either input.
        """

    @with_phil
    def modify_select(self, space2: SpaceID, op: int=...):
        """(SpaceID space2, INT op=SELECT_OR)

        Refines the hyperslab selection of this dataspace (self) using the
        hyperslab selection from a second dataspace. The default operation
        is a union, extending the selection to any parts selected in the second
        dataspace.
        """

    @with_phil
    def is_regular_hyperslab(self):
        """() => BOOL

        Determine whether a hyperslab selection is regular.
        """

    @with_phil
    def get_regular_hyperslab(self):
        """() => (TUPLE start, TUPLE stride, TUPLE count, TUPLE block)

        Retrieve a regular hyperslab selection.
        """
SELECT_NOOP = ...
SELECT_SET = ...
SELECT_OR = ...
SELECT_AND = ...
SELECT_XOR = ...
SELECT_NOTB = ...
SELECT_NOTA = ...
SELECT_APPEND = ...
SELECT_PREPEND = ...
SELECT_INVALID = ...
ALL = ...
UNLIMITED = ...
NO_CLASS = ...
SCALAR = ...
SIMPLE = ...
SEL_ERROR = ...
SEL_NONE = ...
SEL_POINTS = ...
SEL_HYPERSLABS = ...
SEL_ALL = ...

@with_phil
def create(class_code: int):
    """(INT class_code) => SpaceID

    Create a new HDF5 dataspace object, of the given class.
    Legal values are SCALAR and SIMPLE.
    """

@with_phil
def create_simple(dims_tpl: object, max_dims_tpl: object=None):
    """(TUPLE dims_tpl, TUPLE max_dims_tpl) => SpaceID

    Create a simple (slab) dataspace from a tuple of dimensions.
    Every element of dims_tpl must be a positive integer.

    You can optionally specify the maximum dataspace size. The
    special value UNLIMITED, as an element of max_dims, indicates
    an unlimited dimension.
    """

@with_phil
def decode(buf):
    """(STRING buf) => SpaceID

    Unserialize a dataspace.  Bear in mind you can also use the native
    Python pickling machinery to do this.
    """