# This file was generated by stubgen-pyx v0.2.10 from h5py\h5t.pyx

"""
HDF5 "H5T" data-type API

This module contains the datatype identifier class TypeID, and its
subclasses which represent things like integer/float/compound identifiers.
The majority of the H5T API is presented as methods on these identifiers.
"""
import platform
import re
from collections import namedtuple

import numpy as cnp
import numpy as np

from ._objects import ObjectID, with_phil
from .defs import *
from .h5 import get_config
from .h5r import Reference, RegionReference


class TypeID(ObjectID):
    """
    Base class for type identifiers (implements common operations)

    * Hashable: If committed or locked
    * Equality: Logical H5T comparison
    """

    def __hash__(self):
        ...

    def __richcmp__(self, other: object, how: int):
        ...

    def __copy__(self):
        ...

    @property
    def dtype(self):
        """ A Numpy-style dtype object representing this object.
        """

    @with_phil
    def commit(self, group: ObjectID, name: str, lcpl: ObjectID=None):
        """(ObjectID group, STRING name, PropID lcpl=None)

        Commit this (transient) datatype to a named datatype in a file.
        If present, lcpl may be a link creation property list.
        """

    @with_phil
    def committed(self):
        """() => BOOL is_comitted

        Determine if a given type object is named (T) or transient (F).
        """

    @with_phil
    def copy(self):
        """() => TypeID

        Create a copy of this type object.
        """

    @with_phil
    def equal(self, typeid: TypeID):
        """(TypeID typeid) => BOOL

        Logical comparison between datatypes.  Also called by
        Python's "==" operator.
        """

    @with_phil
    def lock(self):
        """()

        Lock this datatype, which makes it immutable and indestructible.
        Once locked, it can't be unlocked.
        """

    @with_phil
    def get_class(self):
        """() => INT classcode

        Determine the datatype's class code.
        """

    @with_phil
    def set_size(self, size: int):
        """(UINT size)

        Set the total size of the datatype, in bytes.
        """

    @with_phil
    def get_size(self):
        """ () => INT size

        Determine the total size of a datatype, in bytes.
        """

    @with_phil
    def get_super(self):
        """() => TypeID

        Determine the parent type of an array, enumeration or vlen datatype.
        """

    @with_phil
    def detect_class(self, classtype: int):
        """(INT classtype) => BOOL class_is_present

        Determine if a member of the given class exists in a compound
        datatype.  The search is recursive.
        """

    @with_phil
    def encode(self):
        """() => STRING

        Serialize an HDF5 type.  Bear in mind you can also use the
        native Python pickle/unpickle machinery to do this.  The
        returned string may contain binary values, including NULLs.
        """

    @with_phil
    def get_create_plist(self):
        """ () => PropTCID

        Create and return a new copy of the datatype creation property list
        used when this datatype was created.
        """

    def __reduce__(self):
        ...

    def __setstate__(self, state: str):
        ...

class TypeArrayID(TypeID):
    """
    Represents an array datatype
    """

    @with_phil
    def get_array_ndims(self):
        """() => INT rank

        Get the rank of the given array datatype.
        """

    @with_phil
    def get_array_dims(self):
        """() => TUPLE dimensions

        Get the dimensions of the given array datatype as
        a tuple of integers.
        """

class TypeOpaqueID(TypeID):
    """
    Represents an opaque type
    """

    @with_phil
    def set_tag(self, tag: str):
        """(STRING tag)

        Set a string describing the contents of an opaque datatype.
        Limited to 256 characters.
        """

    @with_phil
    def get_tag(self):
        """() => STRING tag

        Get the tag associated with an opaque datatype.
        """

class TypeStringID(TypeID):
    """
    String datatypes, both fixed and vlen.
    """

    @with_phil
    def is_variable_str(self):
        """() => BOOL is_variable

        Determine if the given string datatype is a variable-length string.
        """

    @with_phil
    def get_cset(self):
        """() => INT character_set

        Retrieve the character set used for a string.
        """

    @with_phil
    def set_cset(self, cset: int):
        """(INT character_set)

        Set the character set used for a string.
        """

    @with_phil
    def get_strpad(self):
        """() => INT padding_type

        Get the padding type.  Legal values are:

        STR_NULLTERM
            NULL termination only (C style)

        STR_NULLPAD
            Pad buffer with NULLs

        STR_SPACEPAD
            Pad buffer with spaces (FORTRAN style)
        """

    @with_phil
    def set_strpad(self, pad: int):
        """(INT pad)

        Set the padding type.  Legal values are:

        STR_NULLTERM
            NULL termination only (C style)

        STR_NULLPAD
            Pad buffer with NULLs

        STR_SPACEPAD
            Pad buffer with spaces (FORTRAN style)
        """

class TypeVlenID(TypeID):
    """
    Non-string vlen datatypes.
    """

class TypeTimeID(TypeID):
    """
    Unix-style time_t (deprecated)
    """

class TypeBitfieldID(TypeID):
    """
    HDF5 bitfield type
    """

    @with_phil
    def get_order(self):
        """() => INT order

        Obtain the byte order of the datatype; one of:

        - ORDER_LE
        - ORDER_BE
        """

class TypeReferenceID(TypeID):
    """
    HDF5 object or region reference
    """

class TypeAtomicID(TypeID):
    """
    Base class for atomic datatypes (float or integer)
    """

    @with_phil
    def get_order(self):
        """() => INT order

        Obtain the byte order of the datatype; one of:

        - ORDER_LE
        - ORDER_BE
        """

    @with_phil
    def set_order(self, order: int):
        """(INT order)

        Set the byte order of the datatype; one of:

        - ORDER_LE
        - ORDER_BE
        """

    @with_phil
    def get_precision(self):
        """() => UINT precision

        Get the number of significant bits (excludes padding).
        """

    @with_phil
    def set_precision(self, precision: int):
        """(UINT precision)

        Set the number of significant bits (excludes padding).
        """

    @with_phil
    def get_offset(self):
        """() => INT offset

        Get the offset of the first significant bit.
        """

    @with_phil
    def set_offset(self, offset: int):
        """(UINT offset)

        Set the offset of the first significant bit.
        """

    @with_phil
    def get_pad(self):
        """() => (INT lsb_pad_code, INT msb_pad_code)

        Determine the padding type.  Possible values are:

        - PAD_ZERO
        - PAD_ONE
        - PAD_BACKGROUND
        """

    @with_phil
    def set_pad(self, lsb: int, msb: int):
        """(INT lsb_pad_code, INT msb_pad_code)

        Set the padding type.  Possible values are:

        - PAD_ZERO
        - PAD_ONE
        - PAD_BACKGROUND
        """

class TypeIntegerID(TypeAtomicID):
    """
    Integer atomic datatypes
    """

    @with_phil
    def get_sign(self):
        """() => INT sign

        Get the "signedness" of the datatype; one of:

        SGN_NONE
            Unsigned

        SGN_2
            Signed 2's complement
        """

    @with_phil
    def set_sign(self, sign: int):
        """(INT sign)

        Set the "signedness" of the datatype; one of:

        SGN_NONE
            Unsigned

        SGN_2
            Signed 2's complement
        """

class TypeFloatID(TypeAtomicID):
    """
    Floating-point atomic datatypes
    """

    @with_phil
    def get_fields(self):
        """() => TUPLE field_info

        Get information about floating-point bit fields.  See the HDF5
        docs for a full description.  Tuple has the following members:

        0. UINT spos
        1. UINT epos
        2. UINT esize
        3. UINT mpos
        4. UINT msize
        """

    @with_phil
    def set_fields(self, spos: int, epos: int, esize: int, mpos: int, msize: int):
        """(UINT spos, UINT epos, UINT esize, UINT mpos, UINT msize)

        Set floating-point bit fields.  Refer to the HDF5 docs for
        argument definitions.
        """

    @with_phil
    def get_ebias(self):
        """() => UINT ebias

        Get the exponent bias.
        """

    @with_phil
    def set_ebias(self, ebias: int):
        """(UINT ebias)

        Set the exponent bias.
        """

    @with_phil
    def get_norm(self):
        """() => INT normalization_code

        Get the normalization strategy.  Legal values are:

        - NORM_IMPLIED
        - NORM_MSBSET
        - NORM_NONE
        """

    @with_phil
    def set_norm(self, norm: int):
        """(INT normalization_code)

        Set the normalization strategy.  Legal values are:

        - NORM_IMPLIED
        - NORM_MSBSET
        - NORM_NONE
        """

    @with_phil
    def get_inpad(self):
        """() => INT pad_code

        Determine the internal padding strategy.  Legal values are:

        - PAD_ZERO
        - PAD_ONE
        - PAD_BACKGROUND
        """

    @with_phil
    def set_inpad(self, pad_code: int):
        """(INT pad_code)

        Set the internal padding strategy.  Legal values are:

        - PAD_ZERO
        - PAD_ONE
        - PAD_BACKGROUND
        """

class TypeComplexID(TypeAtomicID):
    """Native complex number datatypes"""

class TypeCompositeID(TypeID):
    """
    Base class for enumerated and compound types.
    """

    @with_phil
    def get_nmembers(self):
        """() => INT number_of_members

        Determine the number of members in a compound or enumerated type.
        """

    @with_phil
    def get_member_name(self, member: int):
        """(INT member) => STRING name

        Determine the name of a member of a compound or enumerated type,
        identified by its index (0 <= member < nmembers).
        """

    @with_phil
    def get_member_index(self, name: str):
        """(STRING name) => INT index

        Determine the index of a member of a compound or enumerated datatype
        identified by a string name.
        """

class TypeCompoundID(TypeCompositeID):
    """
    Represents a compound datatype
    """

    @with_phil
    def get_member_class(self, member: int):
        """(INT member) => INT class

        Determine the datatype class of the member of a compound type,
        identified by its index (0 <= member < nmembers).
        """

    @with_phil
    def get_member_offset(self, member: int):
        """(INT member) => INT offset

        Determine the offset, in bytes, of the beginning of the specified
        member of a compound datatype.
        """

    @with_phil
    def get_member_type(self, member: int):
        """(INT member) => TypeID

        Create a copy of a member of a compound datatype, identified by its
        index.
        """

    @with_phil
    def insert(self, name: str, offset: int, field: TypeID):
        """(STRING name, UINT offset, TypeID field)

        Add a named member datatype to a compound datatype.  The parameter
        offset indicates the offset from the start of the compound datatype,
        in bytes.
        """

    @with_phil
    def pack(self):
        """()

        Recursively removes padding (introduced on account of e.g. compiler
        alignment rules) from a compound datatype.
        """

class TypeEnumID(TypeCompositeID):
    """
    Represents an enumerated type
    """

    @with_phil
    def enum_insert(self, name: str, value: int):
        """(STRING name, INT/LONG value)

        Define a new member of an enumerated type.  The value will be
        automatically converted to the base type defined for this enum.  If
        the conversion results in overflow, the value will be silently
        clipped.
        """

    @with_phil
    def enum_nameof(self, value: int):
        """(LONG value) => STRING name

        Determine the name associated with the given value.  Due to a
        limitation of the HDF5 library, this can only retrieve names up to
        1023 characters in length.
        """

    @with_phil
    def enum_valueof(self, name: str):
        """(STRING name) => LONG value

        Get the value associated with an enum name.
        """

    @with_phil
    def get_member_value(self, idx: int):
        """(UINT index) => LONG value

        Determine the value for the member at the given zero-based index.
        """
cfg = get_config()
_UNAME_MACHINE = platform.uname()[4]
_IS_PPC64 = _UNAME_MACHINE == 'ppc64'
_IS_PPC64LE = _UNAME_MACHINE == 'ppc64le'
NUMPY_RUNTIME_VERSION_TUPLE = ...
NO_CLASS = ...
INTEGER = ...
FLOAT = ...
TIME = ...
STRING = ...
BITFIELD = ...
OPAQUE = ...
COMPOUND = ...
REFERENCE = ...
ENUM = ...
VLEN = ...
ARRAY = ...
COMPLEX = ...
SGN_NONE = ...
SGN_2 = ...
ORDER_LE = ...
ORDER_BE = ...
ORDER_VAX = ...
ORDER_NONE = ...
DIR_DEFAULT = ...
DIR_ASCEND = ...
DIR_DESCEND = ...
STR_NULLTERM = ...
STR_NULLPAD = ...
STR_SPACEPAD = ...
NORM_IMPLIED = ...
NORM_MSBSET = ...
NORM_NONE = ...
CSET_ASCII = ...
PAD_ZERO = ...
PAD_ONE = ...
PAD_BACKGROUND = ...
BKG_NO = ...
BKG_TEMP = ...
BKG_YES = ...
IEEE_F32LE = ...
IEEE_F32BE = ...
IEEE_F64LE = ...
IEEE_F64BE = ...
IEEE_F16BE = ...
IEEE_F16LE = ...
IEEE_F128BE = IEEE_F64BE.copy()
IEEE_F128LE = IEEE_F128BE.copy()
COMPLEX_IEEE_F16LE = ...
COMPLEX_IEEE_F16BE = ...
COMPLEX_IEEE_F32LE = ...
COMPLEX_IEEE_F32BE = ...
COMPLEX_IEEE_F64LE = ...
COMPLEX_IEEE_F64BE = ...
STD_I8LE = ...
STD_I16LE = ...
STD_I32LE = ...
STD_I64LE = ...
STD_I8BE = ...
STD_I16BE = ...
STD_I32BE = ...
STD_I64BE = ...
STD_B8LE = ...
STD_B16LE = ...
STD_B32LE = ...
STD_B64LE = ...
STD_B8BE = ...
STD_B16BE = ...
STD_B32BE = ...
STD_B64BE = ...
STD_U8LE = ...
STD_U16LE = ...
STD_U32LE = ...
STD_U64LE = ...
STD_U8BE = ...
STD_U16BE = ...
STD_U32BE = ...
STD_U64BE = ...
NATIVE_B8 = ...
NATIVE_INT8 = ...
NATIVE_UINT8 = ...
NATIVE_B16 = ...
NATIVE_INT16 = ...
NATIVE_UINT16 = ...
NATIVE_B32 = ...
NATIVE_INT32 = ...
NATIVE_UINT32 = ...
NATIVE_B64 = ...
NATIVE_INT64 = ...
NATIVE_UINT64 = ...
NATIVE_FLOAT = ...
NATIVE_DOUBLE = ...
NATIVE_LDOUBLE = ...
LDOUBLE_LE = NATIVE_LDOUBLE.copy()
LDOUBLE_BE = NATIVE_LDOUBLE.copy()
UNIX_D32LE = ...
UNIX_D64LE = ...
UNIX_D32BE = ...
UNIX_D64BE = ...
STD_REF_OBJ = ...
STD_REF_DSETREG = ...
C_S1 = ...
FORTRAN_S1 = ...
VARIABLE = ...
CSET_UTF8 = ...
PYTHON_OBJECT = ...
NUMPY_VLEN_STRING = ...
ref_dtype = np.dtype('O', metadata={'ref': Reference})
regionref_dtype = np.dtype('O', metadata={'ref': RegionReference})
string_info = namedtuple('string_info', ['encoding', 'length'])

def typewrap(id_: hid_t) -> TypeID:
    ...

@with_phil
def create(classtype: int, size: int):
    """(INT classtype, UINT size) => TypeID

    Create a new HDF5 type object.  Legal class values are
    COMPOUND and OPAQUE.  Use enum_create for enums.
    """

@with_phil
def open(group: ObjectID, name: str, tapl: ObjectID=None):
    """(ObjectID group, STRING name) => TypeID

    Open a named datatype from a file.
    If present, tapl must be a datatype access property list.
    """

@with_phil
def array_create(base: TypeID, dims_tpl: object):
    """(TypeID base, TUPLE dimensions) => TypeArrayID

    Create a new array datatype, using and HDF5 parent type and
    dimensions given via a tuple of positive integers.  "Unlimited"
    dimensions are not allowed.
    """

@with_phil
def enum_create(base: TypeID):
    """(TypeID base) => TypeID

    Create a new enumerated type based on an (integer) parent type.
    """

@with_phil
def vlen_create(base: TypeID):
    """(TypeID base) => TypeID

    Create a new variable-length datatype, using any HDF5 type as a base.

    Although the Python interface can manipulate these types, there is no
    provision for reading/writing vlen data.
    """

@with_phil
def decode(buf: str):
    """(STRING buf) => TypeID

    Deserialize an HDF5 type.  You can also do this with the native
    Python pickling machinery.
    """

def _get_float_dtype_to_hdf5():
    ...

def py_create(dtype_in: object, logical: bool=0, aligned: bool=0) -> TypeID:
    """(OBJECT dtype_in, BOOL logical=False) => TypeID

    Given a Numpy dtype object, generate a byte-for-byte memory-compatible
    HDF5 datatype object.  The result is guaranteed to be transient and
    unlocked.

    :param dtype_in: may be a dtype object, or anything which can be
        converted to a dtype, including strings like '<i4' or an "int".
    :param logical: when this flag is set, instead of returning a byte-for-byte
        identical representation of the type, the function returns the closest
        logically appropriate HDF5 type.  For example, in the case of a "hinted"
        dtype of kind "O" representing a string, it would return an HDF5 variable-
        length string type.
    """

def vlen_dtype(basetype):
    """Make a numpy dtype for an HDF5 variable-length datatype

    For variable-length string dtypes, use :func:`string_dtype` instead.
    """

def string_dtype(encoding='utf-8', length=None):
    """Make a numpy dtype for HDF5 strings

    encoding may be 'utf-8' or 'ascii'.

    length may be an integer for a fixed length string dtype, or None for
    variable length strings. String lengths for HDF5 are counted in bytes,
    not unicode code points.

    For variable length strings, the data should be passed as Python str objects
    if the encoding is 'utf-8', and bytes if it is 'ascii'.
    Starting from NumPy 2.0, it is preferred to pass utf-8 data as variable-width
    NumPy strings (``dtype=numpy.dtypes.StringDType()`` or ``dtype='T'``
    instead of ``dtype=h5py.string_dtype()``).

    For fixed length strings, the data should be numpy fixed length *bytes*
    arrays, regardless of the encoding. Fixed length unicode data is not
    supported.
    """

def enum_dtype(values_dict, basetype=...):
    """Create a NumPy representation of an HDF5 enumerated type

    *values_dict* maps string names to integer values. *basetype* is an
    appropriate integer base dtype large enough to hold the possible options.
    """

def opaque_dtype(np_dtype):
    """Return an equivalent dtype tagged to be stored in an HDF5 opaque type.

    This makes it easy to store numpy data like datetimes for which there is
    no equivalent HDF5 type, but it's not interoperable: other tools won't treat
    the opaque data as datetimes.
    """

def complex_compat_dtype(complex_dtype, names=...):
    """Create a backward-compatible structured dtype for storing complex numbers

    HDF5 1.x does not have a native way to represent complex numbers, so we
    translate them to a compound datatype of 2 floats. HDF5 2.0 added a complex
    datatype, and a future version of h5py will probably use that by default.

    With this function, you can explicitly create datasets and attributes with
    the compatible compound dtype for complex numbers:

        cx_dt = h5py.compound_complex_dtype('<c8')
        ds = f.create_dataset('complex_compat', shape=(100,), dtype=cx_dt)

    Pass a specification for a NumPy complex dtype to control size & endianness.
    """

@with_phil
def special_dtype(**kwds):
    """ Create a new h5py "special" type.  Only one keyword may be given.

    Legal keywords are:

    vlen = basetype
        Base type for HDF5 variable-length datatype. This can be Python
        str type or instance of np.dtype.
        Example: special_dtype( vlen=str )

    enum = (basetype, values_dict)
        Create a NumPy representation of an HDF5 enumerated type.  Provide
        a 2-tuple containing an (integer) base dtype and a dict mapping
        string names to integer values.

    ref = Reference | RegionReference
        Create a NumPy representation of an HDF5 object or region reference
        type.
    """

def check_vlen_dtype(dt):
    """If the dtype represents an HDF5 vlen, returns the Python base class.

    Returns None if the dtype does not represent an HDF5 vlen.
    """

def check_string_dtype(dt):
    """If the dtype represents an HDF5 string, returns a string_info object.

    The returned string_info object holds the encoding and the length.
    The encoding can only be 'utf-8' or 'ascii'. The length may be None
    for a variable-length string, or a fixed length in bytes.

    Returns None if the dtype does not represent an HDF5 string.
    """

def check_enum_dtype(dt):
    """If the dtype represents an HDF5 enumerated type, returns the dictionary
    mapping string names to integer values.

    Returns None if the dtype does not represent an HDF5 enumerated type.
    """

def check_opaque_dtype(dt):
    """Return True if the dtype given is tagged to be stored as HDF5 opaque data
    """

def check_ref_dtype(dt):
    """If the dtype represents an HDF5 reference type, returns the reference
    class (either Reference or RegionReference).

    Returns None if the dtype does not represent an HDF5 reference type.
    """

def check_complex_dtype(dt, names=...):
    """If the dtype represents complex number, return an equivalent NumPy dtype.

    This recognises both real complex dtypes, and the compatible compound dtypes
    produced by complex_compat_dtype(). For the compatible dtypes, the field
    names must match *names*, or pass None to allow any field names.

    Returns None if the dtype does not represent complex numbers.
    """

@with_phil
def check_dtype(**kwds):
    """ Check a dtype for h5py special type "hint" information.  Only one
    keyword may be given.

    vlen = dtype
        If the dtype represents an HDF5 vlen, returns the Python base class.
        Currently only built-in string vlens (str) are supported.  Returns
        None if the dtype does not represent an HDF5 vlen.

    enum = dtype
        If the dtype represents an HDF5 enumerated type, returns the dictionary
        mapping string names to integer values.  Returns None if the dtype does
        not represent an HDF5 enumerated type.

    ref = dtype
        If the dtype represents an HDF5 reference type, returns the reference
        class (either Reference or RegionReference).  Returns None if the dtype
        does not represent an HDF5 reference type.
    """

@with_phil
def convert(src: TypeID, dst: TypeID, n: int, buf: cnp.ndarray, bkg: cnp.ndarray=None, dxpl: ObjectID=None):
    """ (TypeID src, TypeID dst, UINT n, NDARRAY buf, NDARRAY bkg=None,
    PropID dxpl=None)

    Convert n contiguous elements of a buffer in-place.  The array dtype
    is ignored.  The backing buffer is optional; for conversion of compound
    types, a temporary copy of conversion buffer will used for backing if
    one is not supplied.
    """

@with_phil
def find(src: TypeID, dst: TypeID):
    """ (TypeID src, TypeID dst) => TUPLE or None

    Determine if a conversion path exists from src to dst.  Result is None
    or a tuple describing the conversion path.  Currently tuple entries are:

    1. INT need_bkg:    Whether this routine requires a backing buffer.
                        Values are BKG_NO, BKG_TEMP and BKG_YES.
    """