# This file was generated by stubgen-pyx v0.2.12 from h5py\utils.pyx

from numpy import ndarray

from .defs import *


def _test_emalloc(size: int):
    ...

def check_numpy_write(arr: ndarray, space_id: hid_t=-1) -> int:
    ...

def check_numpy_read(arr: ndarray, space_id: hid_t=-1) -> int:
    ...
