steps:
- download: current
  artifact: ${{ parameters.platform }}_wheels
  displayName: Download wheels
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'
- script: |
    python -m pip install --upgrade pip
    pip install tox codecov
  displayName: Install tox
- bash: |
    ls $PIPELINE_WORKSPACE/${{ parameters.platform }}_wheels/
    # Bash's own globbing doesn't like Windows-style paths, so expand it using Python
    WHL_PATH=$(python3 -c "import glob, sys; print(glob.glob(sys.argv[1])[0])" \
               "$PIPELINE_WORKSPACE/${{ parameters.platform }}_wheels/$WHL_FILE")
    echo "Will install wheel from $WHL_PATH"
    tox --installpkg $WHL_PATH
  displayName: Run tests
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'ci/upload_coverage.py'
    arguments: --codecov-token 813fb6da-087d-4b36-a185-5a530cab3455
  displayName: 'Upload codecov data'
